songdata = [["Cutie pie","BSC","2.45"],
["Cutie pie","ADV","4.15"],
["Cutie pie","EXT","5.15"],
["FIRE(DM:V)","BSC","2.8"],
["FIRE(DM:V)","ADV","5.05"],
["FIRE(DM:V)","EXT","6.5"],
["Happy man","BSC","4.8"],
["Happy man","ADV","6.0"],
["Happy man","EXT","7.1"],
["Hypnotica","BSC","3.45"],
["Hypnotica","ADV","4.8"],
["Hypnotica","EXT","5.9"],
["LUCKY? STAFF(DM:V)","BSC","3.65"],
["LUCKY? STAFF(DM:V)","ADV","6.25"],
["LUCKY? STAFF(DM:V)","EXT","8.35"],
["Across the nightmare","BSC","3.85"],
["Across the nightmare","ADV","5.3"],
["Across the nightmare","EXT","6.5"],
["Depend on me","BSC","2.75"],
["Depend on me","ADV","5.2"],
["Depend on me","EXT","6.65"],
["Heaven is a '57 metallic gray","BSC","4.6"],
["Heaven is a '57 metallic gray","ADV","5.85"],
["Heaven is a '57 metallic gray","EXT","7.35"],
["I think about you","BSC","1.6"],
["I think about you","ADV","4.7"],
["I think about you","EXT","5.75"],
["JET WORLD","BSC","4.8"],
["JET WORLD","ADV","5.5"],
["JET WORLD","EXT","6.15"],
["PRIMAL SOUL(DM:2nd)","BSC","3.95"],
["PRIMAL SOUL(DM:2nd)","ADV","6.85"],
["PRIMAL SOUL(DM:2nd)","EXT","8.6"],
["Ska Ska No.1","BSC","3.8"],
["Ska Ska No.1","ADV","4.8"],
["Ska Ska No.1","EXT","5.75"],
["CLASSIC PARTY","BSC","3.25"],
["CLASSIC PARTY","ADV","5.95"],
["CLASSIC PARTY","EXT","6.5"],
["COSMIC COWGIRL","BSC","5.4"],
["COSMIC COWGIRL","ADV","6.35"],
["COSMIC COWGIRL","EXT","7.2"],
["LOUD!","BSC","2.35"],
["LOUD!","ADV","5.5"],
["LOUD!","EXT","6.45"],
["LOUD!","MAS","7.95"],
["MIDNIGHT SPECIAL","BSC","4.15"],
["MIDNIGHT SPECIAL","ADV","5.75"],
["MIDNIGHT SPECIAL","EXT","6.95"],
["P.P.R.","BSC","4.2"],
["P.P.R.","ADV","5.65"],
["P.P.R.","EXT","6.65"],
["SAY WHAT YOU MEAN","BSC","4.1"],
["SAY WHAT YOU MEAN","ADV","6.8"],
["SAY WHAT YOU MEAN","EXT","7.3"],
["STOP SPINNING ME IN CIRCLES","BSC","3.5"],
["STOP SPINNING ME IN CIRCLES","ADV","5.05"],
["STOP SPINNING ME IN CIRCLES","EXT","6.05"],
["CAPTAIN'S VOYAGE","BSC","2.7"],
["CAPTAIN'S VOYAGE","ADV","4.65"],
["CAPTAIN'S VOYAGE","EXT","7.5"],
["CARNIVAL DAY","BSC","3.7"],
["CARNIVAL DAY","ADV","6.55"],
["CARNIVAL DAY","EXT","7.75"],
["CLASSIC PARTY 2","BSC","3.8"],
["CLASSIC PARTY 2","ADV","6.05"],
["CLASSIC PARTY 2","EXT","6.85"],
["DAY DREAM","BSC","7.0"],
["DAY DREAM","ADV","7.8"],
["DAY DREAM","EXT","9.2"],
["DAY DREAM","MAS","9.98"],
["GIANT SLUG","BSC","3.65"],
["GIANT SLUG","ADV","4.85"],
["GIANT SLUG","EXT","5.9"],
["I'M GONNA GET YOU!","BSC","2.45"],
["I'M GONNA GET YOU!","ADV","4.85"],
["I'M GONNA GET YOU!","EXT","6.15"],
["RIGHT ON TIME","BSC","4.15"],
["RIGHT ON TIME","ADV","5.4"],
["RIGHT ON TIME","EXT","6.7"],
["SEA ANEMONES","BSC","3.4"],
["SEA ANEMONES","ADV","5.5"],
["SEA ANEMONES","EXT","7.5"],
["SEA ANEMONES","MAS","8.7"],
["CASSANDRA","BSC","2.9"],
["CASSANDRA","ADV","5.15"],
["CASSANDRA","EXT","6.6"],
["CLASSIC PARTY 3","BSC","4.25"],
["CLASSIC PARTY 3","ADV","5.65"],
["CLASSIC PARTY 3","EXT","6.15"],
["FIRE IN THE DARK","BSC","4.45"],
["FIRE IN THE DARK","ADV","6.2"],
["FIRE IN THE DARK","EXT","8.4"],
["The Least 100sec","BSC","5.2"],
["The Least 100sec","ADV","6.9"],
["The Least 100sec","EXT","9.45"],
["The Least 100sec","MAS","9.96"],
["THREE WORMS","BSC","3.45"],
["THREE WORMS","ADV","6.45"],
["THREE WORMS","EXT","8.6"],
["TIGER, TOO","BSC","4.6"],
["TIGER, TOO","ADV","6.85"],
["TIGER, TOO","EXT","7.8"],
["VOIDDD","BSC","2.15"],
["VOIDDD","ADV","5.8"],
["VOIDDD","EXT","8.65"],
["BLIND","BSC","2.5"],
["BLIND","ADV","3.8"],
["BLIND","EXT","5.4"],
["BLIND","MAS","6.75"],
["BOBBY SUE AND SKINNY JIM","BSC","3.6"],
["BOBBY SUE AND SKINNY JIM","ADV","6.35"],
["BOBBY SUE AND SKINNY JIM","EXT","7.35"],
["Brazilian Anthem","BSC","6.1"],
["Brazilian Anthem","ADV","7.2"],
["Brazilian Anthem","EXT","8.3"],
["E-MAIL ME!","BSC","2.85"],
["E-MAIL ME!","ADV","5.05"],
["E-MAIL ME!","EXT","6.7"],
["FEEL THE EARTH","BSC","1.8"],
["FEEL THE EARTH","ADV","4.0"],
["FEEL THE EARTH","EXT","6.1"],
["FEEL THE EARTH","MAS","7.95"],
["FIREBALL","BSC","4.85"],
["FIREBALL","ADV","6.75"],
["FIREBALL","EXT","7.85"],
["Herring roe","BSC","3.45"],
["Herring roe","ADV","6.3"],
["Herring roe","EXT","9.0"],
["Herring roe","MAS","9.85"],
["hypnotheque","BSC","4.1"],
["hypnotheque","ADV","5.3"],
["hypnotheque","EXT","7.3"],
["MIDNIGHT SUN","BSC","4.3"],
["MIDNIGHT SUN","ADV","5.55"],
["MIDNIGHT SUN","EXT","8.25"],
["plastic imitations","BSC","4.1"],
["plastic imitations","ADV","4.8"],
["plastic imitations","EXT","6.6"],
["STOP THIS TRAIN","BSC","4.2"],
["STOP THIS TRAIN","ADV","5.7"],
["STOP THIS TRAIN","EXT","6.7"],
["Sunflower Girl","BSC","1.55"],
["Sunflower Girl","ADV","3.45"],
["Sunflower Girl","EXT","5.15"],
["Sunflower Girl","MAS","6.4"],
["Yellow Panic Time","BSC","5.15"],
["Yellow Panic Time","ADV","6.0"],
["Yellow Panic Time","EXT","6.95"],
["子供の落書き帳","BSC","7.75"],
["子供の落書き帳","ADV","8.7"],
["子供の落書き帳","EXT","9.4"],
["子供の落書き帳","MAS","9.91"],
["正論","BSC","5.2"],
["正論","ADV","6.45"],
["正論","EXT","7.4"],
["Concertino in Blue","BSC","7.05"],
["Concertino in Blue","ADV","7.95"],
["Concertino in Blue","EXT","8.9"],
["Concertino in Blue","MAS","9.67"],
["Destiny lovers","BSC","4.85"],
["Destiny lovers","ADV","6.75"],
["Destiny lovers","EXT","7.9"],
["GETAWAY","BSC","3.7"],
["GETAWAY","ADV","4.8"],
["GETAWAY","EXT","7.15"],
["innocent world","BSC","1.15"],
["innocent world","ADV","3.05"],
["innocent world","EXT","4.15"],
["jet coaster☆girl","BSC","2.65"],
["jet coaster☆girl","ADV","5.55"],
["jet coaster☆girl","EXT","6.55"],
["MODEL DD2","BSC","7.1"],
["MODEL DD2","ADV","7.9"],
["MODEL DD2","EXT","8.7"],
["MODEL DD2","MAS","9.35"],
["Moonlight Walkin'","BSC","3.75"],
["Moonlight Walkin'","ADV","5.35"],
["Moonlight Walkin'","EXT","7.2"],
["O JIYA","BSC","3.15"],
["O JIYA","ADV","5.95"],
["O JIYA","EXT","8.95"],
["One Phrase Blues","BSC","5.45"],
["One Phrase Blues","ADV","6.6"],
["One Phrase Blues","EXT","8.7"],
["ROCKIN' PARADISE","BSC","4.8"],
["ROCKIN' PARADISE","ADV","6.3"],
["ROCKIN' PARADISE","EXT","8.55"],
["under control","BSC","5.3"],
["under control","ADV","6.55"],
["under control","EXT","7.75"],
["under control","MAS","9.2"],
["WILD RIDE","BSC","4.0"],
["WILD RIDE","ADV","6.2"],
["WILD RIDE","EXT","8.1"],
["蛹","BSC","5.7"],
["蛹","ADV","7.45"],
["蛹","EXT","8.5"],
["スイマーズ","BSC","3.45"],
["スイマーズ","ADV","5.4"],
["スイマーズ","EXT","7.15"],
["誰？","BSC","1.85"],
["誰？","ADV","3.95"],
["誰？","EXT","6.2"],
["誰？","MAS","7.3"],
["begin","BSC","2.3"],
["begin","ADV","6.4"],
["begin","EXT","7.4"],
["BRE∀K DOWN! (GF&DM STYLE)","BSC","2.2"],
["BRE∀K DOWN! (GF&DM STYLE)","ADV","5.85"],
["BRE∀K DOWN! (GF&DM STYLE)","EXT","6.65"],
["cachaca","BSC","5.45"],
["cachaca","ADV","6.5"],
["cachaca","EXT","7.4"],
["CHOCOLATE PHILOSOPHY","BSC","3.75"],
["CHOCOLATE PHILOSOPHY","ADV","5.55"],
["CHOCOLATE PHILOSOPHY","EXT","7.1"],
["Homesick Pt.2&3","BSC","2.4"],
["Homesick Pt.2&3","ADV","5.9"],
["Homesick Pt.2&3","EXT","7.35"],
["Infinite","BSC","5.05"],
["Infinite","ADV","6.1"],
["Infinite","EXT","7.05"],
["KISS ME GOODBYE!","BSC","4.1"],
["KISS ME GOODBYE!","ADV","5.85"],
["KISS ME GOODBYE!","EXT","8.3"],
["MODEL DD3","BSC","6.35"],
["MODEL DD3","ADV","8.6"],
["MODEL DD3","EXT","9.2"],
["MODEL DD3","MAS","9.87"],
["THE OCEAN AND YOU","BSC","3.65"],
["THE OCEAN AND YOU","ADV","4.35"],
["THE OCEAN AND YOU","EXT","5.45"],
["To the IST","BSC","3.35"],
["To the IST","ADV","5.2"],
["To the IST","EXT","6.15"],
["too late two","BSC","3.3"],
["too late two","ADV","5.35"],
["too late two","EXT","6.95"],
["スタアの恋人","BSC","2.95"],
["スタアの恋人","ADV","5.45"],
["スタアの恋人","EXT","6.95"],
["そっと。","BSC","3.8"],
["そっと。","ADV","5.65"],
["そっと。","EXT","7.25"],
["たまゆら","BSC","5.0"],
["たまゆら","ADV","7.7"],
["たまゆら","EXT","8.65"],
["たまゆら","MAS","9.0"],
["ツミナガラ... と彼女は謂ふ","BSC","6.45"],
["ツミナガラ... と彼女は謂ふ","ADV","7.4"],
["ツミナガラ... と彼女は謂ふ","EXT","8.35"],
["人にやさしく","BSC","1.55"],
["人にやさしく","ADV","4.4"],
["人にやさしく","EXT","6.4"],
["三毛猫ロック","BSC","5.7"],
["三毛猫ロック","ADV","6.8"],
["三毛猫ロック","EXT","7.3"],
["美丽的家乡","BSC","3.35"],
["美丽的家乡","ADV","5.8"],
["美丽的家乡","EXT","6.65"],
["わすれもの","BSC","2.35"],
["わすれもの","ADV","5.0"],
["わすれもの","EXT","5.85"],
["わすれもの","MAS","7.45"],
["7★7★7★","BSC","4.15"],
["7★7★7★","ADV","5.8"],
["7★7★7★","EXT","7.9"],
["Black horizon","BSC","4.9"],
["Black horizon","ADV","6.8"],
["Black horizon","EXT","7.75"],
["DIAMONDS","BSC","1.55"],
["DIAMONDS","ADV","4.5"],
["DIAMONDS","EXT","5.0"],
["GET READY","BSC","1.6"],
["GET READY","ADV","3.95"],
["GET READY","EXT","5.7"],
["GET READY","MAS","6.85"],
["I'm a loser","BSC","3.25"],
["I'm a loser","ADV","4.95"],
["I'm a loser","EXT","7.0"],
["MAD BLAST","BSC","5.5"],
["MAD BLAST","ADV","7.0"],
["MAD BLAST","EXT","8.3"],
["MAD BLAST","MAS","8.8"],
["MODEL DD4","BSC","6.2"],
["MODEL DD4","ADV","7.25"],
["MODEL DD4","EXT","9.05"],
["MODEL DD4","MAS","9.82"],
["S.P.I.P.","BSC","2.3"],
["S.P.I.P.","ADV","4.5"],
["S.P.I.P.","EXT","6.05"],
["S.P.I.P.","MAS","7.45"],
["TIERRA BUENA","BSC","3.6"],
["TIERRA BUENA","ADV","6.05"],
["TIERRA BUENA","EXT","7.65"],
["Utopia","BSC","3.65"],
["Utopia","ADV","5.45"],
["Utopia","EXT","7.5"],
["月光蝶","BSC","4.6"],
["月光蝶","ADV","6.35"],
["月光蝶","EXT","7.15"],
["大見解","BSC","2.4"],
["大見解","ADV","5.35"],
["大見解","EXT","6.7"],
["チカラ","BSC","3.65"],
["チカラ","ADV","6.2"],
["チカラ","EXT","7.3"],
["涙のregret","BSC","4.8"],
["涙のregret","ADV","5.95"],
["涙のregret","EXT","8.25"],
["花の唄","BSC","3.25"],
["花の唄","ADV","5.5"],
["花の唄","EXT","6.4"],
["万華鏡","BSC","4.25"],
["万華鏡","ADV","5.7"],
["万華鏡","EXT","7.25"],
["万華鏡","MAS","8.05"],
["林檎と蜂蜜","BSC","4.7"],
["林檎と蜂蜜","ADV","6.45"],
["林檎と蜂蜜","EXT","7.25"],
["Agnus Dei","BSC","5.25"],
["Agnus Dei","ADV","6.35"],
["Agnus Dei","EXT","8.15"],
["Agnus Dei","MAS","8.9"],
["cockpit","BSC","4.9"],
["cockpit","ADV","6.7"],
["cockpit","EXT","8.65"],
["cockpit","MAS","9.35"],
["Funky sonic World","BSC","4.0"],
["Funky sonic World","ADV","7.1"],
["Funky sonic World","EXT","9.0"],
["Funky sonic World","MAS","9.62"],
["GET IT ALL","BSC","3.15"],
["GET IT ALL","ADV","6.0"],
["GET IT ALL","EXT","7.35"],
["joker","BSC","4.8"],
["joker","ADV","6.5"],
["joker","EXT","8.8"],
["Libra","BSC","2.05"],
["Libra","ADV","3.1"],
["Libra","EXT","4.15"],
["Libra","MAS","5.8"],
["mint candy ☆ citrus drop","BSC","2.15"],
["mint candy ☆ citrus drop","ADV","4.25"],
["mint candy ☆ citrus drop","EXT","6.2"],
["mint candy ☆ citrus drop","MAS","7.6"],
["MODEL DD5","BSC","5.65"],
["MODEL DD5","ADV","7.45"],
["MODEL DD5","EXT","8.8"],
["MODEL DD5","MAS","9.75"],
["SA-DA-ME","BSC","2.6"],
["SA-DA-ME","ADV","4.75"],
["SA-DA-ME","EXT","6.4"],
["Timepiece phase II","BSC","7.5"],
["Timepiece phase II","ADV","8.6"],
["Timepiece phase II","EXT","9.0"],
["Timepiece phase II","MAS","9.4"],
["カゴノトリ","BSC","3.1"],
["カゴノトリ","ADV","7.3"],
["カゴノトリ","EXT","8.3"],
["この子の七つのお祝いに","BSC","6.5"],
["この子の七つのお祝いに","ADV","7.55"],
["この子の七つのお祝いに","EXT","8.65"],
["しかられ日和","BSC","3.15"],
["しかられ日和","ADV","5.35"],
["しかられ日和","EXT","7.1"],
["蒼白","BSC","3.2"],
["蒼白","ADV","6.15"],
["蒼白","EXT","7.55"],
["蒼白","MAS","8.55"],
["大切なもの","BSC","1.5"],
["大切なもの","ADV","4.15"],
["大切なもの","EXT","6.65"],
["ヒマワリ","BSC","4.25"],
["ヒマワリ","ADV","5.95"],
["ヒマワリ","EXT","7.45"],
["ヘリコプター","BSC","2.5"],
["ヘリコプター","ADV","5.05"],
["ヘリコプター","EXT","6.2"],
["Dedication","BSC","2.2"],
["Dedication","ADV","3.4"],
["Dedication","EXT","4.95"],
["Dedication","MAS","6.7"],
["Dragon Blade","BSC","4.5"],
["Dragon Blade","ADV","5.7"],
["Dragon Blade","EXT","6.75"],
["Dream Again...","BSC","2.65"],
["Dream Again...","ADV","4.8"],
["Dream Again...","EXT","6.1"],
["MODEL DD6","BSC","6.9"],
["MODEL DD6","ADV","8.2"],
["MODEL DD6","EXT","9.05"],
["MONSTER TREE","BSC","2.3"],
["MONSTER TREE","ADV","4.1"],
["MONSTER TREE","EXT","6.25"],
["Orbital Velocity","BSC","4.2"],
["Orbital Velocity","ADV","5.65"],
["Orbital Velocity","EXT","7.25"],
["prism","BSC","2.35"],
["prism","ADV","4.75"],
["prism","EXT","6.75"],
["prism","MAS","7.5"],
["Reaching for the Stars","BSC","4.55"],
["Reaching for the Stars","ADV","6.9"],
["Reaching for the Stars","EXT","8.2"],
["Real ～Lサイズの夢～","BSC","3.65"],
["Real ～Lサイズの夢～","ADV","5.65"],
["Real ～Lサイズの夢～","EXT","6.6"],
["☆shining☆(GF&dm style)","BSC","2.95"],
["☆shining☆(GF&dm style)","ADV","4.95"],
["☆shining☆(GF&dm style)","EXT","6.2"],
["Tail Spin","BSC","3.3"],
["Tail Spin","ADV","4.6"],
["Tail Spin","EXT","6.3"],
["Tail Spin","MAS","8.0"],
["WE ARE","BSC","2.5"],
["WE ARE","ADV","5.6"],
["WE ARE","EXT","7.0"],
["YARA TUM KAHAN?","BSC","3.25"],
["YARA TUM KAHAN?","ADV","6.0"],
["YARA TUM KAHAN?","EXT","7.8"],
["鬼姫","BSC","5.3"],
["鬼姫","ADV","6.7"],
["鬼姫","EXT","8.4"],
["鬼姫","MAS","9.7"],
["こたつとみかん","BSC","3.2"],
["こたつとみかん","ADV","4.95"],
["こたつとみかん","EXT","6.15"],
["青春狂騒曲","BSC","3.15"],
["青春狂騒曲","ADV","4.3"],
["青春狂騒曲","EXT","6.9"],
["二人はラブラブ(仮)","BSC","3.5"],
["二人はラブラブ(仮)","ADV","5.7"],
["二人はラブラブ(仮)","EXT","7.4"],
["明鏡止水","BSC","4.6"],
["明鏡止水","ADV","7.55"],
["明鏡止水","EXT","8.95"],
["明鏡止水","MAS","9.4"],
["AFTER A HARD DAY","BSC","3.25"],
["AFTER A HARD DAY","ADV","5.65"],
["AFTER A HARD DAY","EXT","7.45"],
["ancient breeze","BSC","5.45"],
["ancient breeze","ADV","6.6"],
["ancient breeze","EXT","8.35"],
["Desert Rose","BSC","3.95"],
["Desert Rose","ADV","6.1"],
["Desert Rose","EXT","7.2"],
["Die Zauberflöte","BSC","6.0"],
["Die Zauberflöte","ADV","7.2"],
["Die Zauberflöte","EXT","8.15"],
["Die Zauberflöte","MAS","8.95"],
["Endless cruising","BSC","3.0"],
["Endless cruising","ADV","5.8"],
["Endless cruising","EXT","7.25"],
["ESCAPE TO THE SKY★彡","BSC","3.85"],
["ESCAPE TO THE SKY★彡","ADV","5.65"],
["ESCAPE TO THE SKY★彡","EXT","6.75"],
["Fairy Tales","BSC","3.7"],
["Fairy Tales","ADV","5.95"],
["Fairy Tales","EXT","7.55"],
["Fairy Tales","MAS","8.35"],
["Gently, the rain sings for me","BSC","4.2"],
["Gently, the rain sings for me","ADV","5.4"],
["Gently, the rain sings for me","EXT","6.95"],
["going up","BSC","3.6"],
["going up","ADV","5.5"],
["going up","EXT","8.35"],
["HEAVEN'S COCKTAIL","BSC","3.75"],
["HEAVEN'S COCKTAIL","ADV","6.45"],
["HEAVEN'S COCKTAIL","EXT","8.75"],
["Little Prayer","BSC","5.85"],
["Little Prayer","ADV","7.25"],
["Little Prayer","EXT","8.6"],
["Little Prayer","MAS","9.3"],
["mushroom boy","BSC","3.3"],
["mushroom boy","ADV","4.8"],
["mushroom boy","EXT","7.1"],
["Plastic Umbrella","BSC","3.45"],
["Plastic Umbrella","ADV","5.55"],
["Plastic Umbrella","EXT","7.15"],
["rebirth of love","BSC","2.1"],
["rebirth of love","ADV","3.45"],
["rebirth of love","EXT","4.75"],
["rebirth of love","MAS","6.4"],
["Say","BSC","3.05"],
["Say","ADV","5.8"],
["Say","EXT","6.9"],
["White tornado","BSC","5.0"],
["White tornado","ADV","6.85"],
["White tornado","EXT","8.7"],
["You can't do it if you try","BSC","4.0"],
["You can't do it if you try","ADV","5.45"],
["You can't do it if you try","EXT","6.65"],
["哀愁のコリゴリラ","BSC","3.15"],
["哀愁のコリゴリラ","ADV","5.3"],
["哀愁のコリゴリラ","EXT","6.95"],
["孤高の花","BSC","2.7"],
["孤高の花","ADV","4.85"],
["孤高の花","EXT","6.15"],
["三度笠ポン太は今日も行く","BSC","3.1"],
["三度笠ポン太は今日も行く","ADV","6.35"],
["三度笠ポン太は今日も行く","EXT","8.3"],
["タラッタダンス","BSC","2.6"],
["タラッタダンス","ADV","4.5"],
["タラッタダンス","EXT","6.7"],
["にゃんだふる55","BSC","4.1"],
["にゃんだふる55","ADV","6.8"],
["にゃんだふる55","EXT","7.9"],
["ひとりぼっち","BSC","3.6"],
["ひとりぼっち","ADV","5.3"],
["ひとりぼっち","EXT","7.05"],
["ひとりぼっち","MAS","7.95"],
["ルックス","BSC","2.0"],
["ルックス","ADV","6.15"],
["ルックス","EXT","7.3"],
["Atalante","BSC","4.0"],
["Atalante","ADV","6.35"],
["Atalante","EXT","8.2"],
["CaptivAte～裁き～","BSC","4.3"],
["CaptivAte～裁き～","ADV","5.65"],
["CaptivAte～裁き～","EXT","6.7"],
["GLIDE","BSC","3.6"],
["GLIDE","ADV","5.7"],
["GLIDE","EXT","7.65"],
["Green Lime","BSC","4.0"],
["Green Lime","ADV","6.3"],
["Green Lime","EXT","7.4"],
["JJ-road","BSC","4.35"],
["JJ-road","ADV","5.8"],
["JJ-road","EXT","6.95"],
["Magic words ?","BSC","2.9"],
["Magic words ?","ADV","5.4"],
["Magic words ?","EXT","7.3"],
["MODEL DD7","BSC","5.75"],
["MODEL DD7","ADV","7.7"],
["MODEL DD7","EXT","8.6"],
["over there","BSC","6.65"],
["over there","ADV","8.0"],
["over there","EXT","8.95"],
["over there","MAS","9.8"],
["Sing A Well","BSC","1.3"],
["Sing A Well","ADV","4.2"],
["Sing A Well","EXT","5.8"],
["Take My Hand","BSC","4.25"],
["Take My Hand","ADV","5.8"],
["Take My Hand","EXT","7.55"],
["Tizona d'El Cid","BSC","5.25"],
["Tizona d'El Cid","ADV","6.4"],
["Tizona d'El Cid","EXT","8.6"],
["最速逃避行","BSC","3.5"],
["最速逃避行","ADV","5.3"],
["最速逃避行","EXT","7.05"],
["しっぽのロック","BSC","3.55"],
["しっぽのロック","ADV","5.5"],
["しっぽのロック","EXT","6.65"],
["春の歌","BSC","1.1"],
["春の歌","ADV","3.15"],
["春の歌","EXT","5.9"],
["香港☆超特急Z","BSC","2.5"],
["香港☆超特急Z","ADV","5.05"],
["香港☆超特急Z","EXT","6.35"],
["モラトリアム","BSC","3.25"],
["モラトリアム","ADV","5.75"],
["モラトリアム","EXT","8.4"],
["リライト","BSC","1.85"],
["リライト","ADV","4.75"],
["リライト","EXT","6.45"],
["αρχη","BSC","6.55"],
["αρχη","ADV","7.55"],
["αρχη","EXT","8.9"],
["AXIS","BSC","4.3"],
["AXIS","ADV","6.35"],
["AXIS","EXT","8.05"],
["Day's!","BSC","2.65"],
["Day's!","ADV","5.45"],
["Day's!","EXT","8.25"],
["El Dorado","BSC","2.65"],
["El Dorado","ADV","5.9"],
["El Dorado","EXT","8.4"],
["Forever free","BSC","2.25"],
["Forever free","ADV","4.05"],
["Forever free","EXT","6.0"],
["Forever free","MAS","7.6"],
["Micro fin","BSC","4.0"],
["Micro fin","ADV","4.9"],
["Micro fin","EXT","5.8"],
["MODEL FT2","BSC","6.35"],
["MODEL FT2","ADV","7.65"],
["MODEL FT2","EXT","8.45"],
["MODEL FT2","MAS","9.05"],
["MODEL FT2 Miracle Version","BSC","5.0"],
["MODEL FT2 Miracle Version","ADV","7.4"],
["MODEL FT2 Miracle Version","EXT","9.45"],
["MODEL FT2 Miracle Version","MAS","9.99"],
["Purple storm","BSC","5.6"],
["Purple storm","ADV","7.1"],
["Purple storm","EXT","8.35"],
["Ring","BSC","3.35"],
["Ring","ADV","4.55"],
["Ring","EXT","6.5"],
["Ru-Ru-Ru","BSC","3.15"],
["Ru-Ru-Ru","ADV","5.25"],
["Ru-Ru-Ru","EXT","6.35"],
["Venus","BSC","4.15"],
["Venus","ADV","5.45"],
["Venus","EXT","6.5"],
["ZËNITH","BSC","4.0"],
["ZËNITH","ADV","5.35"],
["ZËNITH","EXT","7.8"],
["ギタードライブ","BSC","1.4"],
["ギタードライブ","ADV","3.85"],
["ギタードライブ","EXT","5.55"],
["ギタードライブ","MAS","6.5"],
["虧兎に告ぐ","BSC","5.6"],
["虧兎に告ぐ","ADV","6.65"],
["虧兎に告ぐ","EXT","7.6"],
["差無来!!","BSC","5.0"],
["差無来!!","ADV","7.2"],
["差無来!!","EXT","9.05"],
["七福神","BSC","3.9"],
["七福神","ADV","5.55"],
["七福神","EXT","8.2"],
["全力少年","BSC","1.05"],
["全力少年","ADV","2.85"],
["全力少年","EXT","5.15"],
["ミラージュ・レジデンス","BSC","5.05"],
["ミラージュ・レジデンス","ADV","6.65"],
["ミラージュ・レジデンス","EXT","8.15"],
["戻らない恋","BSC","2.3"],
["戻らない恋","ADV","5.25"],
["戻らない恋","EXT","6.35"],
["大和撫子魂","BSC","3.4"],
["大和撫子魂","ADV","4.65"],
["大和撫子魂","EXT","6.45"],
["繚乱ヒットチャート","BSC","4.15"],
["繚乱ヒットチャート","ADV","5.75"],
["繚乱ヒットチャート","EXT","7.65"],
["5-10","BSC","3.05"],
["5-10","ADV","5.05"],
["5-10","EXT","7.0"],
["5-10","MAS","7.95"],
["Charismatic","BSC","3.1"],
["Charismatic","ADV","5.4"],
["Charismatic","EXT","7.0"],
["DEADMAN’S BED","BSC","2.0"],
["DEADMAN’S BED","ADV","3.4"],
["DEADMAN’S BED","EXT","4.8"],
["DEADMAN’S BED","MAS","6.15"],
["First Date","BSC","2.1"],
["First Date","ADV","4.3"],
["First Date","EXT","6.35"],
["First Date","MAS","8.0"],
["GORI GORI","BSC","3.75"],
["GORI GORI","ADV","5.85"],
["GORI GORI","EXT","7.2"],
["How do you feel?","BSC","1.35"],
["How do you feel?","ADV","4.05"],
["How do you feel?","EXT","6.85"],
["Immortal Bind","BSC","3.65"],
["Immortal Bind","ADV","4.4"],
["Immortal Bind","EXT","8.2"],
["MODEL DD8","BSC","5.9"],
["MODEL DD8","ADV","6.75"],
["MODEL DD8","EXT","7.45"],
["MODEL DD8","MAS","8.7"],
["murmur twins (guitar pop ver.)","BSC","3.95"],
["murmur twins (guitar pop ver.)","ADV","5.45"],
["murmur twins (guitar pop ver.)","EXT","6.85"],
["PRIME LIGHT","BSC","5.4"],
["PRIME LIGHT","ADV","7.05"],
["PRIME LIGHT","EXT","8.45"],
["R#1","BSC","4.3"],
["R#1","ADV","5.45"],
["R#1","EXT","6.9"],
["Raining Sunshine","BSC","2.6"],
["Raining Sunshine","ADV","4.8"],
["Raining Sunshine","EXT","7.25"],
["RЁVOLUTIΦN","BSC","4.35"],
["RЁVOLUTIΦN","ADV","6.05"],
["RЁVOLUTIΦN","EXT","7.8"],
["Slang","BSC","4.75"],
["Slang","ADV","5.95"],
["Slang","EXT","7.3"],
["Strike Party!!!","BSC","3.8"],
["Strike Party!!!","ADV","5.35"],
["Strike Party!!!","EXT","6.9"],
["Swimming In Love","BSC","2.85"],
["Swimming In Love","ADV","4.7"],
["Swimming In Love","EXT","6.9"],
["TABIDACHI","BSC","3.6"],
["TABIDACHI","ADV","5.7"],
["TABIDACHI","EXT","7.45"],
["The Messenger(not decorated)","BSC","3.35"],
["The Messenger(not decorated)","ADV","5.55"],
["The Messenger(not decorated)","EXT","7.1"],
["True Love and Valentines","BSC","2.05"],
["True Love and Valentines","ADV","4.75"],
["True Love and Valentines","EXT","6.75"],
["True Love and Valentines","MAS","8.05"],
["Vertigo","BSC","3.75"],
["Vertigo","ADV","5.4"],
["Vertigo","EXT","6.45"],
["Zigzag Life","BSC","4.95"],
["Zigzag Life","ADV","6.95"],
["Zigzag Life","EXT","8.6"],
["一網打尽","BSC","5.55"],
["一網打尽","ADV","6.8"],
["一網打尽","EXT","8.9"],
["一網打尽","MAS","9.4"],
["ガラナ","BSC","1.75"],
["ガラナ","ADV","3.5"],
["ガラナ","EXT","5.95"],
["極東史記","BSC","4.6"],
["極東史記","ADV","6.35"],
["極東史記","EXT","7.25"],
["恋は臆病","BSC","4.2"],
["恋は臆病","ADV","6.7"],
["恋は臆病","EXT","8.0"],
["太陽～T・A・I・Y・O～(ANOTHER SENSE EDITION)","BSC","4.0"],
["太陽～T・A・I・Y・O～(ANOTHER SENSE EDITION)","ADV","5.85"],
["太陽～T・A・I・Y・O～(ANOTHER SENSE EDITION)","EXT","6.95"],
["A.DOGMA","BSC","7.7"],
["A.DOGMA","ADV","9.15"],
["A.DOGMA","EXT","9.65"],
["A.DOGMA","MAS","9.97"],
["ATOMS","BSC","3.15"],
["ATOMS","ADV","5.4"],
["ATOMS","EXT","7.2"],
["Blue Forest","BSC","5.7"],
["Blue Forest","ADV","6.6"],
["Blue Forest","EXT","7.9"],
["Blue Forest","MAS","8.5"],
["Dynamis","BSC","6.0"],
["Dynamis","ADV","7.1"],
["Dynamis","EXT","8.6"],
["Dynamis","MAS","9.25"],
["Electric Lady","BSC","4.25"],
["Electric Lady","ADV","6.05"],
["Electric Lady","EXT","8.65"],
["FORCE Interval Build","BSC","5.4"],
["FORCE Interval Build","ADV","6.85"],
["FORCE Interval Build","EXT","8.0"],
["FORCE Interval Build","MAS","9.25"],
["LAST SCENE","BSC","2.3"],
["LAST SCENE","ADV","4.15"],
["LAST SCENE","EXT","5.75"],
["LAST SCENE","MAS","7.3"],
["Mannequin","BSC","2.85"],
["Mannequin","ADV","5.35"],
["Mannequin","EXT","6.75"],
["Opus Life","BSC","2.5"],
["Opus Life","ADV","5.5"],
["Opus Life","EXT","6.8"],
["Opus Life","MAS","7.95"],
["Piece of History","BSC","3.5"],
["Piece of History","ADV","5.45"],
["Piece of History","EXT","7.7"],
["Power Game","BSC","3.45"],
["Power Game","ADV","6.45"],
["Power Game","EXT","8.95"],
["Rock to Infinity","BSC","6.6"],
["Rock to Infinity","ADV","8.55"],
["Rock to Infinity","EXT","9.25"],
["Rock to Infinity","MAS","9.97"],
["TENGU","BSC","4.65"],
["TENGU","ADV","6.15"],
["TENGU","EXT","8.6"],
["Terpsichore","BSC","2.2"],
["Terpsichore","ADV","3.85"],
["Terpsichore","EXT","5.5"],
["Terpsichore","MAS","6.55"],
["The Sound of Truth","BSC","3.4"],
["The Sound of Truth","ADV","4.85"],
["The Sound of Truth","EXT","8.75"],
["VANESSA -転生編-","BSC","4.35"],
["VANESSA -転生編-","ADV","6.15"],
["VANESSA -転生編-","EXT","7.4"],
["VANESSA -転生編-","MAS","9.2"],
["からふるぱすてる","BSC","4.5"],
["からふるぱすてる","ADV","5.8"],
["からふるぱすてる","EXT","7.3"],
["鏡花水月楼(GFDM EDITION)","BSC","3.6"],
["鏡花水月楼(GFDM EDITION)","ADV","6.05"],
["鏡花水月楼(GFDM EDITION)","EXT","7.15"],
["ゴーイング マイ ウェイ！","BSC","2.95"],
["ゴーイング マイ ウェイ！","ADV","4.9"],
["ゴーイング マイ ウェイ！","EXT","7.2"],
["ゴーイング マイ ウェイ！","MAS","7.8"],
["創聖のアクエリオン","BSC","1.3"],
["創聖のアクエリオン","ADV","3.6"],
["創聖のアクエリオン","EXT","6.1"],
["田んぼの田","BSC","2.95"],
["田んぼの田","ADV","5.9"],
["田んぼの田","EXT","7.15"],
["ヒコーキ","BSC","4.0"],
["ヒコーキ","ADV","5.45"],
["ヒコーキ","EXT","7.05"],
["ヒコーキ","MAS","8.2"],
["ヒトリアソビ","BSC","2.25"],
["ヒトリアソビ","ADV","4.9"],
["ヒトリアソビ","EXT","6.9"],
["ヒトリアソビ","MAS","8.35"],
["腐斯偽堕日本","BSC","2.65"],
["腐斯偽堕日本","ADV","4.95"],
["腐斯偽堕日本","EXT","7.1"],
["腐斯偽堕日本","MAS","8.75"],
["流氷の去りて","BSC","5.55"],
["流氷の去りて","ADV","7.05"],
["流氷の去りて","EXT","8.85"],
["凛として咲く花の如く","BSC","1.2"],
["凛として咲く花の如く","ADV","5.7"],
["凛として咲く花の如く","EXT","7.25"],
["1/n","BSC","3.25"],
["1/n","ADV","5.4"],
["1/n","EXT","6.9"],
["Catharsis Garden","BSC","3.15"],
["Catharsis Garden","ADV","4.25"],
["Catharsis Garden","EXT","6.9"],
["Chronos","BSC","4.7"],
["Chronos","ADV","5.45"],
["Chronos","EXT","7.1"],
["Chronos","MAS","8.6"],
["Driven Shooter","BSC","4.3"],
["Driven Shooter","ADV","6.2"],
["Driven Shooter","EXT","7.9"],
["ENCORE CONQUEST","BSC","7.45"],
["ENCORE CONQUEST","ADV","8.85"],
["ENCORE CONQUEST","EXT","9.4"],
["ENCORE CONQUEST","MAS","9.75"],
["four-leaf","BSC","3.45"],
["four-leaf","ADV","5.35"],
["four-leaf","EXT","6.4"],
["Highway star","BSC","4.25"],
["Highway star","ADV","5.8"],
["Highway star","EXT","7.75"],
["humming rabbit","BSC","2.15"],
["humming rabbit","ADV","4.05"],
["humming rabbit","EXT","6.1"],
["humming rabbit","MAS","7.25"],
["Icicles","BSC","4.95"],
["Icicles","ADV","6.65"],
["Icicles","EXT","8.95"],
["I wanna kiss you","BSC","2.25"],
["I wanna kiss you","ADV","4.8"],
["I wanna kiss you","EXT","5.85"],
["Jungle","BSC","6.4"],
["Jungle","ADV","8.95"],
["Jungle","EXT","9.6"],
["Jungle","MAS","9.95"],
["Lost in Blue","BSC","2.3"],
["Lost in Blue","ADV","4.2"],
["Lost in Blue","EXT","6.2"],
["NIL","BSC","4.1"],
["NIL","ADV","5.25"],
["NIL","EXT","6.85"],
["OVER THE LIMIT！","BSC","3.65"],
["OVER THE LIMIT！","ADV","4.45"],
["OVER THE LIMIT！","EXT","7.3"],
["Red","BSC","4.0"],
["Red","ADV","5.35"],
["Red","EXT","7.3"],
["Siren","BSC","3.8"],
["Siren","ADV","4.9"],
["Siren","EXT","6.75"],
["Sonne","BSC","6.9"],
["Sonne","ADV","8.15"],
["Sonne","EXT","8.85"],
["Sonne","MAS","9.93"],
["The Ascension","BSC","3.15"],
["The Ascension","ADV","4.85"],
["The Ascension","EXT","7.15"],
["The Ascension","MAS","7.95"],
["Through the Fire and Flames","BSC","4.2"],
["Through the Fire and Flames","ADV","6.4"],
["Through the Fire and Flames","EXT","8.45"],
["Through the Fire and Flames","MAS","9.3"],
["Vampire Killer","BSC","2.85"],
["Vampire Killer","ADV","5.15"],
["Vampire Killer","EXT","7.65"],
["walk with you","BSC","2.1"],
["walk with you","ADV","4.25"],
["walk with you","EXT","6.0"],
["Walnuts","BSC","3.7"],
["Walnuts","ADV","4.85"],
["Walnuts","EXT","6.55"],
["Walnuts","MAS","7.7"],
["Water frame","BSC","2.95"],
["Water frame","ADV","4.5"],
["Water frame","EXT","7.1"],
["イジワルなあなた","BSC","2.35"],
["イジワルなあなた","ADV","5.7"],
["イジワルなあなた","EXT","7.1"],
["ガラスの小舟","BSC","2.9"],
["ガラスの小舟","ADV","4.45"],
["ガラスの小舟","EXT","5.25"],
["恐怖の右脳改革","BSC","6.45"],
["恐怖の右脳改革","ADV","7.3"],
["恐怖の右脳改革","EXT","9.1"],
["恐怖の右脳改革","MAS","9.45"],
["心の折れたエンジェル","BSC","2.45"],
["心の折れたエンジェル","ADV","4.85"],
["心の折れたエンジェル","EXT","7.35"],
["こなもん屋人情歌","BSC","2.85"],
["こなもん屋人情歌","ADV","5.7"],
["こなもん屋人情歌","EXT","6.5"],
["情熱 fun! fun!","BSC","1.2"],
["情熱 fun! fun!","ADV","4.7"],
["情熱 fun! fun!","EXT","5.75"],
["風神雲龍伝","BSC","5.55"],
["風神雲龍伝","ADV","6.9"],
["風神雲龍伝","EXT","8.45"],
["風神雲龍伝","MAS","9.0"],
["ブルーバード","BSC","1.1"],
["ブルーバード","ADV","3.95"],
["ブルーバード","EXT","5.95"],
["罠","BSC","2.1"],
["罠","ADV","3.25"],
["罠","EXT","6.35"],
["10,000,000,000","BSC","4.35"],
["10,000,000,000","ADV","5.9"],
["10,000,000,000","EXT","8.45"],
["10,000,000,000","MAS","9.3"],
["Ascetic","BSC","5.3"],
["Ascetic","ADV","6.65"],
["Ascetic","EXT","8.65"],
["Ascetic","MAS","8.95"],
["Before Daybreak","BSC","3.75"],
["Before Daybreak","ADV","6.45"],
["Before Daybreak","EXT","9.05"],
["Believing","BSC","2.3"],
["Believing","ADV","4.3"],
["Believing","EXT","6.75"],
["Blue planet","BSC","3.8"],
["Blue planet","ADV","6.3"],
["Blue planet","EXT","7.3"],
["CALAMITY PHOENIX","BSC","4.65"],
["CALAMITY PHOENIX","ADV","6.85"],
["CALAMITY PHOENIX","EXT","8.45"],
["CALAMITY PHOENIX","MAS","8.9"],
["Confession","BSC","1.45"],
["Confession","ADV","3.85"],
["Confession","EXT","7.1"],
["Crack","BSC","3.7"],
["Crack","ADV","5.25"],
["Crack","EXT","7.95"],
["Croquette","BSC","2.7"],
["Croquette","ADV","4.2"],
["Croquette","EXT","6.35"],
["Deep Forest","BSC","3.5"],
["Deep Forest","ADV","5.2"],
["Deep Forest","EXT","7.05"],
["Eau Rouge","BSC","4.2"],
["Eau Rouge","ADV","5.9"],
["Eau Rouge","EXT","6.85"],
["Eau Rouge","MAS","7.55"],
["Egocentricity","BSC","2.7"],
["Egocentricity","ADV","5.85"],
["Egocentricity","EXT","6.45"],
["Einherjar","BSC","3.35"],
["Einherjar","ADV","6.35"],
["Einherjar","EXT","7.75"],
["Einherjar","MAS","9.15"],
["Excavation Damage","BSC","3.25"],
["Excavation Damage","ADV","4.65"],
["Excavation Damage","EXT","6.5"],
["Excavation Damage","MAS","7.55"],
["Hunter～どうしても欲しいもの～","BSC","3.1"],
["Hunter～どうしても欲しいもの～","ADV","4.35"],
["Hunter～どうしても欲しいもの～","EXT","7.3"],
["Hunter～どうしても欲しいもの～","MAS","7.9"],
["HYPER JET LAND","BSC","4.1"],
["HYPER JET LAND","ADV","6.25"],
["HYPER JET LAND","EXT","8.0"],
["IMI","BSC","3.25"],
["IMI","ADV","5.55"],
["IMI","EXT","8.15"],
["IMITATION TOUCH","BSC","4.0"],
["IMITATION TOUCH","ADV","5.8"],
["IMITATION TOUCH","EXT","7.95"],
["Invincible","BSC","3.45"],
["Invincible","ADV","4.65"],
["Invincible","EXT","6.2"],
["I Want It All","BSC","2.45"],
["I Want It All","ADV","3.85"],
["I Want It All","EXT","7.4"],
["KAISER PHOENIX","BSC","5.75"],
["KAISER PHOENIX","ADV","6.85"],
["KAISER PHOENIX","EXT","8.25"],
["KAISER PHOENIX","MAS","8.8"],
["Keep Ur Dreams","BSC","1.75"],
["Keep Ur Dreams","ADV","3.75"],
["Keep Ur Dreams","EXT","6.4"],
["kiss me","BSC","2.1"],
["kiss me","ADV","4.25"],
["kiss me","EXT","6.15"],
["Limitless Possibility","BSC","3.35"],
["Limitless Possibility","ADV","4.6"],
["Limitless Possibility","EXT","7.45"],
["Limitless Possibility","MAS","7.95"],
["Love☆Carnival","BSC","2.85"],
["Love☆Carnival","ADV","5.7"],
["Love☆Carnival","EXT","7.1"],
["MODEL DD9","BSC","6.45"],
["MODEL DD9","ADV","8.35"],
["MODEL DD9","EXT","8.95"],
["MODEL DD9","MAS","9.8"],
["No Way For One Will","BSC","3.9"],
["No Way For One Will","ADV","4.9"],
["No Way For One Will","EXT","7.15"],
["On top of the world","BSC","4.75"],
["On top of the world","ADV","6.2"],
["On top of the world","EXT","8.55"],
["photon","BSC","3.45"],
["photon","ADV","6.2"],
["photon","EXT","8.35"],
["photon","MAS","8.95"],
["Piranha","BSC","1.85"],
["Piranha","ADV","5.25"],
["Piranha","EXT","6.35"],
["Shake and Shout!!","BSC","3.75"],
["Shake and Shout!!","ADV","5.8"],
["Shake and Shout!!","EXT","6.8"],
["Shake and Shout!!","MAS","7.75"],
["Sky Runner","BSC","3.15"],
["Sky Runner","ADV","5.2"],
["Sky Runner","EXT","8.1"],
["Sky Runner","MAS","8.9"],
["Stay away","BSC","1.0"],
["Stay away","ADV","1.95"],
["Stay away","EXT","4.95"],
["Two Hurt","BSC","1.7"],
["Two Hurt","ADV","5.7"],
["Two Hurt","EXT","8.25"],
["White wings","BSC","3.55"],
["White wings","ADV","4.95"],
["White wings","EXT","6.65"],
["WILD CREATURES","BSC","1.15"],
["WILD CREATURES","ADV","4.75"],
["WILD CREATURES","EXT","7.9"],
["X-treme Grade","BSC","4.6"],
["X-treme Grade","ADV","6.0"],
["X-treme Grade","EXT","9.1"],
["X-treme Grade","MAS","9.57"],
["You've Got 2 Get Me","BSC","2.55"],
["You've Got 2 Get Me","ADV","5.35"],
["You've Got 2 Get Me","EXT","7.95"],
["青い鳥","BSC","2.25"],
["青い鳥","ADV","4.1"],
["青い鳥","EXT","6.1"],
["憧れのボディービル!!","BSC","2.6"],
["憧れのボディービル!!","ADV","5.25"],
["憧れのボディービル!!","EXT","8.25"],
["嘘","BSC","1.15"],
["嘘","ADV","5.0"],
["嘘","EXT","7.2"],
["クリーンクリーン","BSC","3.1"],
["クリーンクリーン","ADV","5.85"],
["クリーンクリーン","EXT","7.55"],
["紅蓮の焔","BSC","3.25"],
["紅蓮の焔","ADV","4.5"],
["紅蓮の焔","EXT","7.25"],
["幻想花","BSC","4.5"],
["幻想花","ADV","5.8"],
["幻想花","EXT","8.35"],
["さよなら僕自身","BSC","3.45"],
["さよなら僕自身","ADV","6.6"],
["さよなら僕自身","EXT","8.3"],
["空色デイズ","BSC","1.2"],
["空色デイズ","ADV","3.05"],
["空色デイズ","EXT","6.35"],
["太陽の花","BSC","1.2"],
["太陽の花","ADV","3.1"],
["太陽の花","EXT","6.6"],
["天庭 おとこのこ編","BSC","3.95"],
["天庭 おとこのこ編","ADV","5.45"],
["天庭 おとこのこ編","EXT","7.65"],
["天庭 おとこのこ編","MAS","8.65"],
["人間進化論","BSC","1.1"],
["人間進化論","ADV","3.9"],
["人間進化論","EXT","5.3"],
["ヒカリ","BSC","1.35"],
["ヒカリ","ADV","4.15"],
["ヒカリ","EXT","6.7"],
["ほしふり","BSC","2.65"],
["ほしふり","ADV","5.65"],
["ほしふり","EXT","6.75"],
["三毛猫JIVE&ジャイブ","BSC","4.85"],
["三毛猫JIVE&ジャイブ","ADV","6.2"],
["三毛猫JIVE&ジャイブ","EXT","7.75"],
["三毛猫JIVE&ジャイブ","MAS","8.4"],
["モナリザ","BSC","1.05"],
["モナリザ","ADV","3.15"],
["モナリザ","EXT","6.9"],
["Adrenaline","BSC","3.4"],
["Adrenaline","ADV","5.15"],
["Adrenaline","EXT","6.55"],
["Adverse Criticism","BSC","4.65"],
["Adverse Criticism","ADV","6.6"],
["Adverse Criticism","EXT","8.35"],
["AREA 51","BSC","3.1"],
["AREA 51","ADV","5.15"],
["AREA 51","EXT","8.05"],
["Around 40","BSC","3.65"],
["Around 40","ADV","4.85"],
["Around 40","EXT","9.4"],
["Bangin' Breaks","BSC","4.1"],
["Bangin' Breaks","ADV","6.05"],
["Bangin' Breaks","EXT","7.9"],
["BEFORE I DECAY","BSC","2.5"],
["BEFORE I DECAY","ADV","3.9"],
["BEFORE I DECAY","EXT","7.7"],
["Big Wave","BSC","3.35"],
["Big Wave","ADV","4.85"],
["Big Wave","EXT","6.7"],
["blue moon","BSC","4.9"],
["blue moon","ADV","6.8"],
["blue moon","EXT","8.65"],
["blue moon","MAS","9.25"],
["Brown blizzard","BSC","5.65"],
["Brown blizzard","ADV","7.1"],
["Brown blizzard","EXT","9.1"],
["Brown blizzard","MAS","9.96"],
["Chance","BSC","3.75"],
["Chance","ADV","4.9"],
["Chance","EXT","6.75"],
["chAngE","BSC","1.7"],
["chAngE","ADV","3.1"],
["chAngE","EXT","5.65"],
["Chinese Snowy Dance","BSC","4.6"],
["Chinese Snowy Dance","ADV","6.55"],
["Chinese Snowy Dance","EXT","8.9"],
["Chinese Snowy Dance","MAS","9.4"],
["Come Back Alive","BSC","4.1"],
["Come Back Alive","ADV","5.3"],
["Come Back Alive","EXT","9.9"],
["cosmic agenda","BSC","2.4"],
["cosmic agenda","ADV","5.15"],
["cosmic agenda","EXT","7.8"],
["DAWN","BSC","4.2"],
["DAWN","ADV","7.0"],
["DAWN","EXT","8.85"],
["DESTINY","BSC","3.9"],
["DESTINY","ADV","6.0"],
["DESTINY","EXT","8.85"],
["drop","BSC","3.8"],
["drop","ADV","5.95"],
["drop","EXT","7.35"],
["EXCELSIOR DIVE","BSC","5.75"],
["EXCELSIOR DIVE","ADV","7.05"],
["EXCELSIOR DIVE","EXT","8.55"],
["EXCELSIOR DIVE","MAS","9.0"],
["FIFTH GIG","BSC","4.9"],
["FIFTH GIG","ADV","8.45"],
["FIFTH GIG","EXT","9.9"],
["FIFTH GIG TYPE II","BSC","4.15"],
["FIFTH GIG TYPE II","ADV","6.85"],
["FIFTH GIG TYPE II","EXT","9.65"],
["gloom","BSC","3.7"],
["gloom","ADV","5.4"],
["gloom","EXT","8.35"],
["HIT IN THE USA","BSC","1.1"],
["HIT IN THE USA","ADV","3.8"],
["HIT IN THE USA","EXT","6.7"],
["I can be!!","BSC","3.85"],
["I can be!!","ADV","5.9"],
["I can be!!","EXT","8.7"],
["Illuminati～光を求める者たち～","BSC","5.35"],
["Illuminati～光を求める者たち～","ADV","6.65"],
["Illuminati～光を求める者たち～","EXT","7.95"],
["Illuminati～光を求める者たち～","MAS","8.7"],
["Jailbreak","BSC","4.45"],
["Jailbreak","ADV","5.95"],
["Jailbreak","EXT","8.65"],
["Lepton","BSC","4.5"],
["Lepton","ADV","5.65"],
["Lepton","EXT","7.9"],
["Love Rox!","BSC","3.2"],
["Love Rox!","ADV","4.1"],
["Love Rox!","EXT","5.9"],
["no way ...","BSC","3.25"],
["no way ...","ADV","4.95"],
["no way ...","EXT","7.5"],
["Pink Bird","BSC","3.15"],
["Pink Bird","ADV","5.1"],
["Pink Bird","EXT","7.2"],
["REALIZE","BSC","5.3"],
["REALIZE","ADV","7.75"],
["REALIZE","EXT","9.87"],
["Right on time (Ryu☆Remix)","BSC","2.3"],
["Right on time (Ryu☆Remix)","ADV","5.3"],
["Right on time (Ryu☆Remix)","EXT","8.4"],
["Sacred Oath (GFDM EDITION)","BSC","3.2"],
["Sacred Oath (GFDM EDITION)","ADV","4.5"],
["Sacred Oath (GFDM EDITION)","EXT","7.0"],
["SIX DIMENSION","BSC","5.45"],
["SIX DIMENSION","ADV","7.35"],
["SIX DIMENSION","EXT","8.9"],
["SIX DIMENSION","MAS","9.4"],
["Spiral Wind","BSC","3.5"],
["Spiral Wind","ADV","5.55"],
["Spiral Wind","EXT","9.3"],
["Spring Pain","BSC","2.9"],
["Spring Pain","ADV","4.3"],
["Spring Pain","EXT","6.85"],
["The 勇気","BSC","1.65"],
["The 勇気","ADV","3.9"],
["The 勇気","EXT","6.3"],
["Victory!","BSC","2.3"],
["Victory!","ADV","4.45"],
["Victory!","EXT","8.55"],
["X-Plan","BSC","2.7"],
["X-Plan","ADV","6.65"],
["X-Plan","EXT","8.15"],
["アンマー","BSC","2.55"],
["アンマー","ADV","3.9"],
["アンマー","EXT","5.45"],
["イバラノミチ","BSC","3.5"],
["イバラノミチ","ADV","4.95"],
["イバラノミチ","EXT","6.85"],
["ヴィーナスとジーザス","BSC","1.2"],
["ヴィーナスとジーザス","ADV","4.3"],
["ヴィーナスとジーザス","EXT","5.7"],
["君の知らない物語","BSC","1.25"],
["君の知らない物語","ADV","2.75"],
["君の知らない物語","EXT","6.05"],
["牛乳特急便 -まとめきれないRomantic style-","BSC","4.2"],
["牛乳特急便 -まとめきれないRomantic style-","ADV","7.0"],
["牛乳特急便 -まとめきれないRomantic style-","EXT","8.3"],
["黒髪乱れし修羅となりて","BSC","4.35"],
["黒髪乱れし修羅となりて","ADV","5.45"],
["黒髪乱れし修羅となりて","EXT","8.2"],
["ゲームより愛を込めて","BSC","6.2"],
["ゲームより愛を込めて","ADV","7.6"],
["ゲームより愛を込めて","EXT","8.6"],
["ゲームより愛を込めて","MAS","9.3"],
["幻想雷神記","BSC","4.25"],
["幻想雷神記","ADV","6.35"],
["幻想雷神記","EXT","8.8"],
["幻想雷神記","MAS","9.25"],
["サヨナラナミダ","BSC","4.0"],
["サヨナラナミダ","ADV","6.45"],
["サヨナラナミダ","EXT","8.1"],
["じょいふる","BSC","1.25"],
["じょいふる","ADV","3.75"],
["じょいふる","EXT","6.9"],
["衝動がえがいた どうしようもないストーリー","BSC","1.85"],
["衝動がえがいた どうしようもないストーリー","ADV","5.5"],
["衝動がえがいた どうしようもないストーリー","EXT","6.85"],
["卒業","BSC","4.05"],
["卒業","ADV","5.2"],
["卒業","EXT","6.5"],
["ダイヤモンドロマンス","BSC","3.4"],
["ダイヤモンドロマンス","ADV","5.05"],
["ダイヤモンドロマンス","EXT","6.65"],
["たからもの","BSC","3.35"],
["たからもの","ADV","4.55"],
["たからもの","EXT","8.15"],
["ナキムシの凱旋","BSC","4.4"],
["ナキムシの凱旋","ADV","6.55"],
["ナキムシの凱旋","EXT","9.15"],
["虹の彼方","BSC","1.6"],
["虹の彼方","ADV","4.2"],
["虹の彼方","EXT","6.7"],
["バタフライ狂想曲","BSC","3.75"],
["バタフライ狂想曲","ADV","6.3"],
["バタフライ狂想曲","EXT","7.75"],
["百鬼夜行","BSC","7.6"],
["百鬼夜行","ADV","8.15"],
["百鬼夜行","EXT","8.65"],
["風／雷","BSC","2.35"],
["風／雷","ADV","5.05"],
["風／雷","EXT","7.75"],
["前髪","BSC","2.1"],
["前髪","ADV","3.85"],
["前髪","EXT","8.0"],
["紫の月","BSC","3.25"],
["紫の月","ADV","5.85"],
["紫の月","EXT","7.2"],
["明鏡止水 - Stop The Fire Mix","BSC","3.75"],
["明鏡止水 - Stop The Fire Mix","ADV","5.9"],
["明鏡止水 - Stop The Fire Mix","EXT","8.8"],
["優勢オーバードーズ","BSC","1.05"],
["優勢オーバードーズ","ADV","5.85"],
["優勢オーバードーズ","EXT","8.1"],
["行き過ぎて後に","BSC","3.7"],
["行き過ぎて後に","ADV","4.85"],
["行き過ぎて後に","EXT","7.55"],
["夢について TYPE B","BSC","2.9"],
["夢について TYPE B","ADV","5.2"],
["夢について TYPE B","EXT","6.4"],
["夢について TYPE C","BSC","3.75"],
["夢について TYPE C","ADV","6.0"],
["夢について TYPE C","EXT","9.2"],
["800nm","BSC","2.65"],
["800nm","ADV","5.65"],
["800nm","EXT","8.0"],
["CHAIN REACTION feat.NO+CHIN","BSC","3.05"],
["CHAIN REACTION feat.NO+CHIN","ADV","6.65"],
["CHAIN REACTION feat.NO+CHIN","EXT","7.9"],
["concon～INAReMIX～","BSC","1.3"],
["concon～INAReMIX～","ADV","5.8"],
["concon～INAReMIX～","EXT","8.85"],
["Cosmic Hurricane (GFDM ver.)","BSC","3.7"],
["Cosmic Hurricane (GFDM ver.)","ADV","5.85"],
["Cosmic Hurricane (GFDM ver.)","EXT","8.15"],
["Cosmic Hurricane (GFDM ver.)","MAS","8.9"],
["Devil Fish Dumpling","BSC","3.9"],
["Devil Fish Dumpling","ADV","5.85"],
["Devil Fish Dumpling","EXT","8.85"],
["DOUBLE IMPACT","BSC","4.45"],
["DOUBLE IMPACT","ADV","5.85"],
["DOUBLE IMPACT","EXT","8.4"],
["Dragontail Butterfly","BSC","2.4"],
["Dragontail Butterfly","ADV","6.9"],
["Dragontail Butterfly","EXT","8.25"],
["Eastern Lariat","BSC","4.15"],
["Eastern Lariat","ADV","6.5"],
["Eastern Lariat","EXT","8.65"],
["Eastern Lariat","MAS","9.25"],
["ETERNAL BLAZE","BSC","1.3"],
["ETERNAL BLAZE","ADV","5.25"],
["ETERNAL BLAZE","EXT","7.8"],
["FLOWER -TLION69 Remix-","BSC","4.4"],
["FLOWER -TLION69 Remix-","ADV","5.95"],
["FLOWER -TLION69 Remix-","EXT","8.25"],
["Freeky Technique","BSC","2.2"],
["Freeky Technique","ADV","5.7"],
["Freeky Technique","EXT","7.7"],
["FRIENDSHIP","BSC","3.75"],
["FRIENDSHIP","ADV","6.6"],
["FRIENDSHIP","EXT","7.85"],
["Genesis Creation Narrative","BSC","5.0"],
["Genesis Creation Narrative","ADV","6.55"],
["Genesis Creation Narrative","EXT","8.75"],
["Genesis Creation Narrative","MAS","9.65"],
["Give Me MORE!!","BSC","4.35"],
["Give Me MORE!!","ADV","6.5"],
["Give Me MORE!!","EXT","8.4"],
["Gong!","BSC","2.95"],
["Gong!","ADV","4.9"],
["Gong!","EXT","7.6"],
["Graviton","BSC","3.85"],
["Graviton","ADV","6.1"],
["Graviton","EXT","8.35"],
["Hard distance","BSC","4.75"],
["Hard distance","ADV","7.0"],
["Hard distance","EXT","7.95"],
["Hard distance","MAS","8.4"],
["I'm so Happy (Rockin' ver.)","BSC","2.45"],
["I'm so Happy (Rockin' ver.)","ADV","6.2"],
["I'm so Happy (Rockin' ver.)","EXT","7.95"],
["LISTEN TO THE STEREO!!","BSC","1.7"],
["LISTEN TO THE STEREO!!","ADV","5.4"],
["LISTEN TO THE STEREO!!","EXT","7.25"],
["LOVE WAR!!","BSC","2.0"],
["LOVE WAR!!","ADV","5.4"],
["LOVE WAR!!","EXT","6.75"],
["MODEL DD10","BSC","5.2"],
["MODEL DD10","ADV","6.8"],
["MODEL DD10","EXT","8.7"],
["MODEL DD10","MAS","9.55"],
["Moon of Muse","BSC","3.0"],
["Moon of Muse","ADV","5.75"],
["Moon of Muse","EXT","7.2"],
["NEW LEGEND","BSC","3.1"],
["NEW LEGEND","ADV","4.45"],
["NEW LEGEND","EXT","8.6"],
["ONLY ONE","BSC","1.95"],
["ONLY ONE","ADV","6.4"],
["ONLY ONE","EXT","7.75"],
["Orange Flower Garden","BSC","1.05"],
["Orange Flower Garden","ADV","5.7"],
["Orange Flower Garden","EXT","7.15"],
["overviews","BSC","4.75"],
["overviews","ADV","6.4"],
["overviews","EXT","9.0"],
["overviews","MAS","9.96"],
["Plum","BSC","4.35"],
["Plum","ADV","5.7"],
["Plum","EXT","8.15"],
["POWER","BSC","2.9"],
["POWER","ADV","4.6"],
["POWER","EXT","6.3"],
["Predator's Crypto Pt.1","BSC","4.75"],
["Predator's Crypto Pt.1","ADV","5.85"],
["Predator's Crypto Pt.1","EXT","8.05"],
["Predator's Crypto Pt.1","MAS","8.85"],
["Predator's Crypto Pt.2","BSC","4.5"],
["Predator's Crypto Pt.2","ADV","6.3"],
["Predator's Crypto Pt.2","EXT","8.35"],
["Predator's Crypto Pt.2","MAS","9.1"],
["Raidillon","BSC","3.45"],
["Raidillon","ADV","4.85"],
["Raidillon","EXT","7.75"],
["RePrise","BSC","3.15"],
["RePrise","ADV","4.4"],
["RePrise","EXT","6.85"],
["Restart","BSC","2.75"],
["Restart","ADV","7.25"],
["Restart","EXT","9.4"],
["Riot of Color","BSC","3.4"],
["Riot of Color","ADV","5.45"],
["Riot of Color","EXT","7.75"],
["Riot of Color","MAS","9.05"],
["Rush!!","BSC","2.75"],
["Rush!!","ADV","4.45"],
["Rush!!","EXT","7.1"],
["SCREW DRIVER","BSC","4.05"],
["SCREW DRIVER","ADV","5.15"],
["SCREW DRIVER","EXT","7.7"],
["SCREW DRIVER","MAS","8.2"],
["serial number","BSC","2.0"],
["serial number","ADV","4.2"],
["serial number","EXT","5.65"],
["Shout!!","BSC","2.95"],
["Shout!!","ADV","5.4"],
["Shout!!","EXT","7.1"],
["Snow Goose GFDM ver.","BSC","2.6"],
["Snow Goose GFDM ver.","ADV","6.6"],
["Snow Goose GFDM ver.","EXT","8.95"],
["snow prism (GFDM ver.)","BSC","2.5"],
["snow prism (GFDM ver.)","ADV","4.6"],
["snow prism (GFDM ver.)","EXT","8.3"],
["Snowy India","BSC","2.85"],
["Snowy India","ADV","5.6"],
["Snowy India","EXT","8.75"],
["Snowy India","MAS","9.52"],
["spectrum","BSC","3.35"],
["spectrum","ADV","5.7"],
["spectrum","EXT","7.9"],
["Starlight Parade","BSC","3.9"],
["Starlight Parade","ADV","5.85"],
["Starlight Parade","EXT","8.9"],
["Summer Holiday","BSC","2.0"],
["Summer Holiday","ADV","3.65"],
["Summer Holiday","EXT","6.7"],
["Xenon","BSC","4.6"],
["Xenon","ADV","7.65"],
["Xenon","EXT","8.9"],
["Xenon","MAS","9.5"],
["アーリマン","BSC","4.0"],
["アーリマン","ADV","5.9"],
["アーリマン","EXT","7.85"],
["暗黒舞踏会","BSC","3.4"],
["暗黒舞踏会","ADV","7.05"],
["暗黒舞踏会","EXT","9.15"],
["歌の翼","BSC","2.55"],
["歌の翼","ADV","5.7"],
["歌の翼","EXT","9.0"],
["ギタ・ドラ・jubeat大夏祭りのテーマ","BSC","3.7"],
["ギタ・ドラ・jubeat大夏祭りのテーマ","ADV","6.55"],
["ギタ・ドラ・jubeat大夏祭りのテーマ","EXT","8.2"],
["逆ナンされたのにドタキャン!!","BSC","1.75"],
["逆ナンされたのにドタキャン!!","ADV","5.35"],
["逆ナンされたのにドタキャン!!","EXT","8.55"],
["群青と流星","BSC","2.45"],
["群青と流星","ADV","4.85"],
["群青と流星","EXT","8.15"],
["紅焔","BSC","2.9"],
["紅焔","ADV","6.15"],
["紅焔","EXT","8.3"],
["侯爵夫人の陰謀","BSC","3.25"],
["侯爵夫人の陰謀","ADV","5.85"],
["侯爵夫人の陰謀","EXT","7.85"],
["サムライハート(Some Like It Hot!!)","BSC","2.75"],
["サムライハート(Some Like It Hot!!)","ADV","4.2"],
["サムライハート(Some Like It Hot!!)","EXT","7.15"],
["幸せのかたち","BSC","3.0"],
["幸せのかたち","ADV","5.4"],
["幸せのかたち","EXT","7.0"],
["隅田川夏恋歌～納涼mix","BSC","1.0"],
["隅田川夏恋歌～納涼mix","ADV","4.9"],
["隅田川夏恋歌～納涼mix","EXT","7.1"],
["タイムカプセル","BSC","3.4"],
["タイムカプセル","ADV","5.7"],
["タイムカプセル","EXT","7.2"],
["つぼみ","BSC","2.5"],
["つぼみ","ADV","5.0"],
["つぼみ","EXT","8.35"],
["夏・KOI・ムッシュ!!","BSC","2.85"],
["夏・KOI・ムッシュ!!","ADV","5.05"],
["夏・KOI・ムッシュ!!","EXT","7.45"],
["夏祭り","BSC","1.5"],
["夏祭り","ADV","4.45"],
["夏祭り","EXT","6.2"],
["ハートジャック","BSC","3.65"],
["ハートジャック","ADV","5.35"],
["ハートジャック","EXT","7.2"],
["双つ雲と暁の奏","BSC","4.15"],
["双つ雲と暁の奏","ADV","6.95"],
["双つ雲と暁の奏","EXT","8.85"],
["星夢","BSC","1.0"],
["星夢","ADV","4.0"],
["星夢","EXT","5.9"],
["耳たぶ2号","BSC","2.5"],
["耳たぶ2号","ADV","5.4"],
["耳たぶ2号","EXT","6.95"],
["ヤミクラ","BSC","3.6"],
["ヤミクラ","ADV","5.8"],
["ヤミクラ","EXT","7.45"],
["流星☆JUMP!","BSC","3.35"],
["流星☆JUMP!","ADV","6.75"],
["流星☆JUMP!","EXT","7.95"],
["恋閃繚乱","BSC","1.4"],
["恋閃繚乱","ADV","4.1"],
["恋閃繚乱","EXT","7.85"],
["笑ってたいんだ","BSC","1.3"],
["笑ってたいんだ","ADV","4.85"],
["笑ってたいんだ","EXT","5.95"],
["0時20分のRoulette","BSC","2.4"],
["0時20分のRoulette","ADV","3.65"],
["0時20分のRoulette","EXT","6.9"],
["8 -eight-","BSC","2.95"],
["8 -eight-","ADV","5.2"],
["8 -eight-","EXT","8.8"],
["IX -GITADOROCK ver.-","BSC","3.95"],
["IX -GITADOROCK ver.-","ADV","5.1"],
["IX -GITADOROCK ver.-","EXT","7.25"],
["IX -GITADOROCK ver.-","MAS","9.0"],
["Arena Sexarboris","BSC","2.9"],
["Arena Sexarboris","ADV","6.9"],
["Arena Sexarboris","EXT","8.65"],
["Awaken Ver.G","BSC","3.45"],
["Awaken Ver.G","ADV","4.25"],
["Awaken Ver.G","EXT","7.85"],
["Beautiful Dream","BSC","2.7"],
["Beautiful Dream","ADV","6.0"],
["Beautiful Dream","EXT","8.45"],
["BLUE BOOTS","BSC","4.0"],
["BLUE BOOTS","ADV","5.75"],
["BLUE BOOTS","EXT","8.8"],
["Cassis","BSC","3.7"],
["Cassis","ADV","5.5"],
["Cassis","EXT","8.55"],
["Crazy blooms","BSC","3.85"],
["Crazy blooms","ADV","5.0"],
["Crazy blooms","EXT","7.7"],
["Crazy blooms","MAS","8.4"],
["DIGITAL GIRL","BSC","3.85"],
["DIGITAL GIRL","ADV","5.35"],
["DIGITAL GIRL","EXT","7.6"],
["Don't Break Up","BSC","2.5"],
["Don't Break Up","ADV","4.25"],
["Don't Break Up","EXT","8.9"],
["DRAGON KILLER","BSC","2.2"],
["DRAGON KILLER","ADV","4.8"],
["DRAGON KILLER","EXT","7.25"],
["Elemental Creation -GITADO ROCK ver.-","BSC","3.05"],
["Elemental Creation -GITADO ROCK ver.-","ADV","6.5"],
["Elemental Creation -GITADO ROCK ver.-","EXT","9.2"],
["Empathetic","BSC","1.3"],
["Empathetic","ADV","3.75"],
["Empathetic","EXT","7.85"],
["Endless Chain ～2人でトリガーをひこう～","BSC","1.85"],
["Endless Chain ～2人でトリガーをひこう～","ADV","3.4"],
["Endless Chain ～2人でトリガーをひこう～","EXT","5.95"],
["Engraved Mark","BSC","3.1"],
["Engraved Mark","ADV","6.25"],
["Engraved Mark","EXT","8.6"],
["Evans -TLION69 Remix-","BSC","2.7"],
["Evans -TLION69 Remix-","ADV","4.85"],
["Evans -TLION69 Remix-","EXT","8.55"],
["Factor of adhesion","BSC","2.7"],
["Factor of adhesion","ADV","4.35"],
["Factor of adhesion","EXT","7.95"],
["Fat snail","BSC","2.2"],
["Fat snail","ADV","6.15"],
["Fat snail","EXT","8.75"],
["Fly with me","BSC","3.9"],
["Fly with me","ADV","6.15"],
["Fly with me","EXT","7.6"],
["Fly with me","MAS","8.9"],
["GAIA -GITADORA EDITION-","BSC","2.85"],
["GAIA -GITADORA EDITION-","ADV","5.75"],
["GAIA -GITADORA EDITION-","EXT","7.7"],
["GIGA BREAK","BSC","4.5"],
["GIGA BREAK","ADV","6.25"],
["GIGA BREAK","EXT","8.75"],
["Give Us Kiss!","BSC","1.3"],
["Give Us Kiss!","ADV","3.7"],
["Give Us Kiss!","EXT","7.15"],
["Grapes","BSC","3.2"],
["Grapes","ADV","5.05"],
["Grapes","EXT","8.35"],
["HEART BEAT FORMULA (GITADORA Ver.)","BSC","2.85"],
["HEART BEAT FORMULA (GITADORA Ver.)","ADV","5.2"],
["HEART BEAT FORMULA (GITADORA Ver.)","EXT","8.2"],
["heron -GITADOROCK ver.-","BSC","2.6"],
["heron -GITADOROCK ver.-","ADV","4.75"],
["heron -GITADOROCK ver.-","EXT","7.8"],
["HYENA (Live Edit feat. 96)","BSC","3.2"],
["HYENA (Live Edit feat. 96)","ADV","6.6"],
["HYENA (Live Edit feat. 96)","EXT","9.85"],
["Hyperseven type K","BSC","1.5"],
["Hyperseven type K","ADV","4.3"],
["Hyperseven type K","EXT","8.4"],
["Jasper","BSC","4.05"],
["Jasper","ADV","7.15"],
["Jasper","EXT","8.4"],
["Joyeuse","BSC","4.1"],
["Joyeuse","ADV","6.25"],
["Joyeuse","EXT","9.6"],
["Last Song","BSC","5.2"],
["Last Song","ADV","6.2"],
["Last Song","EXT","8.95"],
["Last Song","MAS","9.87"],
["Like&Love","BSC","3.6"],
["Like&Love","ADV","5.4"],
["Like&Love","EXT","8.5"],
["Link up","BSC","1.5"],
["Link up","ADV","4.0"],
["Link up","EXT","7.25"],
["LOVE & JOY -GITADORA MIX-","BSC","2.05"],
["LOVE & JOY -GITADORA MIX-","ADV","5.55"],
["LOVE & JOY -GITADORA MIX-","EXT","7.5"],
["MANDARA","BSC","1.75"],
["MANDARA","ADV","4.0"],
["MANDARA","EXT","8.7"],
["memento mori -intro-","BSC","3.9"],
["memento mori -intro-","ADV","5.95"],
["memento mori -intro-","EXT","8.75"],
["memento mori -intro-","MAS","9.91"],
["Metallic","BSC","2.5"],
["Metallic","ADV","4.95"],
["Metallic","EXT","6.35"],
["Mighty Wind","BSC","3.8"],
["Mighty Wind","ADV","5.8"],
["Mighty Wind","EXT","8.55"],
["MODEL FT3","BSC","4.45"],
["MODEL FT3","ADV","6.9"],
["MODEL FT3","EXT","8.5"],
["MODEL FT3","MAS","9.2"],
["Mother Tree","BSC","2.95"],
["Mother Tree","ADV","6.6"],
["Mother Tree","EXT","8.35"],
["Mother Tree","MAS","9.15"],
["Never Look Back in Sorrow","BSC","4.05"],
["Never Look Back in Sorrow","ADV","6.2"],
["Never Look Back in Sorrow","EXT","9.25"],
["nightbird lost wing (GITADORA ver.)","BSC","1.8"],
["nightbird lost wing (GITADORA ver.)","ADV","4.5"],
["nightbird lost wing (GITADORA ver.)","EXT","7.85"],
["No pain, No game","BSC","2.45"],
["No pain, No game","ADV","3.85"],
["No pain, No game","EXT","6.95"],
["no where now here","BSC","3.7"],
["no where now here","ADV","5.0"],
["no where now here","EXT","7.0"],
["Obsidian","BSC","3.7"],
["Obsidian","ADV","6.45"],
["Obsidian","EXT","8.75"],
["Obsidian","MAS","9.77"],
["OVERHEAT -Type GD-","BSC","2.6"],
["OVERHEAT -Type GD-","ADV","5.4"],
["OVERHEAT -Type GD-","EXT","6.65"],
["OVERHEAT -Type GD-","MAS","8.45"],
["PATRIOT'S DREAM(美しく花と散れ)","BSC","1.2"],
["PATRIOT'S DREAM(美しく花と散れ)","ADV","4.75"],
["PATRIOT'S DREAM(美しく花と散れ)","EXT","8.25"],
["Polaris","BSC","4.45"],
["Polaris","ADV","6.05"],
["Polaris","EXT","8.1"],
["PUNISHER","BSC","2.95"],
["PUNISHER","ADV","4.95"],
["PUNISHER","EXT","8.85"],
["quaver♪ ギタドラ ver.","BSC","3.2"],
["quaver♪ ギタドラ ver.","ADV","4.85"],
["quaver♪ ギタドラ ver.","EXT","7.45"],
["RAGNAROK","BSC","2.2"],
["RAGNAROK","ADV","4.85"],
["RAGNAROK","EXT","8.4"],
["Red haze","BSC","3.5"],
["Red haze","ADV","4.9"],
["Red haze","EXT","6.7"],
["Red haze","MAS","8.0"],
["Return of the throne","BSC","3.45"],
["Return of the throne","ADV","4.8"],
["Return of the throne","EXT","7.45"],
["ROCKET MAN","BSC","3.9"],
["ROCKET MAN","ADV","5.05"],
["ROCKET MAN","EXT","7.35"],
["Rosetta Stone","BSC","3.7"],
["Rosetta Stone","ADV","5.05"],
["Rosetta Stone","EXT","8.1"],
["Rosetta Stone","MAS","9.05"],
["Run Run","BSC","3.2"],
["Run Run","ADV","4.55"],
["Run Run","EXT","8.35"],
["S. LAUNCHER","BSC","3.2"],
["S. LAUNCHER","ADV","5.6"],
["S. LAUNCHER","EXT","8.1"],
["Sakura Sunrise (GITADORA ver.)","BSC","3.25"],
["Sakura Sunrise (GITADORA ver.)","ADV","5.65"],
["Sakura Sunrise (GITADORA ver.)","EXT","8.25"],
["SAVIOR OF SONG (feat. MY FIRST STORY)","BSC","2.85"],
["SAVIOR OF SONG (feat. MY FIRST STORY)","ADV","5.0"],
["SAVIOR OF SONG (feat. MY FIRST STORY)","EXT","6.4"],
["Screaming Your Faith!!!","BSC","2.25"],
["Screaming Your Faith!!!","ADV","4.7"],
["Screaming Your Faith!!!","EXT","8.55"],
["Second Limit","BSC","2.4"],
["Second Limit","ADV","3.85"],
["Second Limit","EXT","6.5"],
["Shining Wings","BSC","2.6"],
["Shining Wings","ADV","4.65"],
["Shining Wings","EXT","6.5"],
["Shining Wizard","BSC","3.0"],
["Shining Wizard","ADV","5.05"],
["Shining Wizard","EXT","9.1"],
["sola GITADORA ver.","BSC","2.65"],
["sola GITADORA ver.","ADV","6.1"],
["sola GITADORA ver.","EXT","8.8"],
["solitude","BSC","3.7"],
["solitude","ADV","5.85"],
["solitude","EXT","8.65"],
["SPACE DRIVER","BSC","2.1"],
["SPACE DRIVER","ADV","4.25"],
["SPACE DRIVER","EXT","6.85"],
["Spanish Snowy Dance (daybreak ver.)","BSC","4.35"],
["Spanish Snowy Dance (daybreak ver.)","ADV","6.5"],
["Spanish Snowy Dance (daybreak ver.)","EXT","8.95"],
["Speeders","BSC","2.9"],
["Speeders","ADV","4.45"],
["Speeders","EXT","6.45"],
["SPRING BAZOOKA","BSC","3.55"],
["SPRING BAZOOKA","ADV","4.75"],
["SPRING BAZOOKA","EXT","8.1"],
["SPRING BAZOOKA","MAS","9.15"],
["Squeeze -GITADORA Mix-","BSC","1.4"],
["Squeeze -GITADORA Mix-","ADV","3.9"],
["Squeeze -GITADORA Mix-","EXT","7.2"],
["Stella Sinistra","BSC","1.85"],
["Stella Sinistra","ADV","4.95"],
["Stella Sinistra","EXT","9.0"],
["STULTI","BSC","1.8"],
["STULTI","ADV","5.35"],
["STULTI","EXT","9.15"],
["Summer Lady","BSC","2.3"],
["Summer Lady","ADV","5.45"],
["Summer Lady","EXT","6.5"],
["Synergy For Angels (GITADORA Ver.)","BSC","1.45"],
["Synergy For Angels (GITADORA Ver.)","ADV","4.35"],
["Synergy For Angels (GITADORA Ver.)","EXT","8.5"],
["TEAR OFF YOUR CHAIN","BSC","2.6"],
["TEAR OFF YOUR CHAIN","ADV","6.45"],
["TEAR OFF YOUR CHAIN","EXT","9.2"],
["TRICK","BSC","3.4"],
["TRICK","ADV","5.7"],
["TRICK","EXT","7.6"],
["Triple Journey -OJ EDITION-","BSC","2.9"],
["Triple Journey -OJ EDITION-","ADV","5.35"],
["Triple Journey -OJ EDITION-","EXT","7.25"],
["Veneficus Verticis","BSC","3.95"],
["Veneficus Verticis","ADV","6.15"],
["Veneficus Verticis","EXT","8.75"],
["Virga Gigantum","BSC","5.3"],
["Virga Gigantum","ADV","6.35"],
["Virga Gigantum","EXT","7.9"],
["Virga Gigantum","MAS","9.45"],
["ViViD","BSC","2.3"],
["ViViD","ADV","3.85"],
["ViViD","EXT","6.85"],
["VOICE","BSC","2.1"],
["VOICE","ADV","6.2"],
["VOICE","EXT","7.2"],
["ZONE//ALONE","BSC","1.75"],
["ZONE//ALONE","ADV","5.7"],
["ZONE//ALONE","EXT","6.7"],
["愛と勇気の三度笠ポン太","BSC","2.05"],
["愛と勇気の三度笠ポン太","ADV","5.1"],
["愛と勇気の三度笠ポン太","EXT","8.4"],
["愛は不死鳥の様に","BSC","1.7"],
["愛は不死鳥の様に","ADV","5.15"],
["愛は不死鳥の様に","EXT","7.3"],
["天ノ弱","BSC","1.9"],
["天ノ弱","ADV","4.05"],
["天ノ弱","EXT","6.95"],
["雨ノチHello","BSC","2.35"],
["雨ノチHello","ADV","5.7"],
["雨ノチHello","EXT","7.7"],
["アルストロメリア(GITADORA Ver.)","BSC","3.2"],
["アルストロメリア(GITADORA Ver.)","ADV","5.7"],
["アルストロメリア(GITADORA Ver.)","EXT","8.55"],
["いきもの失格","BSC","1.9"],
["いきもの失格","ADV","4.6"],
["いきもの失格","EXT","6.6"],
["お米の美味しい炊き方、そしてお米を食べることによるその効果。","BSC","2.5"],
["お米の美味しい炊き方、そしてお米を食べることによるその効果。","ADV","6.15"],
["お米の美味しい炊き方、そしてお米を食べることによるその効果。","EXT","9.2"],
["俺と愛とロック","BSC","2.9"],
["俺と愛とロック","ADV","6.55"],
["俺と愛とロック","EXT","8.35"],
["カタルシスの月","BSC","3.2"],
["カタルシスの月","ADV","4.25"],
["カタルシスの月","EXT","6.5"],
["ガラス越し→バイなう","BSC","3.7"],
["ガラス越し→バイなう","ADV","5.75"],
["ガラス越し→バイなう","EXT","7.3"],
["キケンな果実","BSC","1.45"],
["キケンな果実","ADV","5.95"],
["キケンな果実","EXT","9.15"],
["君と同じ季節の下","BSC","1.9"],
["君と同じ季節の下","ADV","5.05"],
["君と同じ季節の下","EXT","6.9"],
["狂喜宴舞","BSC","2.25"],
["狂喜宴舞","ADV","4.3"],
["狂喜宴舞","EXT","7.9"],
["叫声","BSC","3.0"],
["叫声","ADV","4.6"],
["叫声","EXT","7.4"],
["キルト","BSC","1.05"],
["キルト","ADV","5.35"],
["キルト","EXT","8.25"],
["空蒼ランデヴー","BSC","2.7"],
["空蒼ランデヴー","ADV","5.8"],
["空蒼ランデヴー","EXT","7.5"],
["ぐっばい my crybaby","BSC","1.6"],
["ぐっばい my crybaby","ADV","4.15"],
["ぐっばい my crybaby","EXT","5.9"],
["クリムゾンゲイト","BSC","4.1"],
["クリムゾンゲイト","ADV","5.55"],
["クリムゾンゲイト","EXT","8.0"],
["クリムゾンゲイト","MAS","9.0"],
["迎撃のフォルテ","BSC","3.4"],
["迎撃のフォルテ","ADV","4.15"],
["迎撃のフォルテ","EXT","7.2"],
["元禄花吹雪","BSC","2.75"],
["元禄花吹雪","ADV","5.75"],
["元禄花吹雪","EXT","8.55"],
["元禄花吹雪","MAS","9.1"],
["こわれそうなもの","BSC","3.4"],
["こわれそうなもの","ADV","6.1"],
["こわれそうなもの","EXT","8.1"],
["金輪際のエレジー","BSC","3.9"],
["金輪際のエレジー","ADV","6.2"],
["金輪際のエレジー","EXT","8.0"],
["最終回STORY","BSC","2.35"],
["最終回STORY","ADV","4.45"],
["最終回STORY","EXT","6.3"],
["去る金合戦","BSC","1.4"],
["去る金合戦","ADV","3.85"],
["去る金合戦","EXT","7.4"],
["此岸の戯事","BSC","3.5"],
["此岸の戯事","ADV","5.85"],
["此岸の戯事","EXT","7.85"],
["辞世テンプレート","BSC","2.6"],
["辞世テンプレート","ADV","4.8"],
["辞世テンプレート","EXT","8.6"],
["情操ディストピア","BSC","2.45"],
["情操ディストピア","ADV","4.75"],
["情操ディストピア","EXT","6.95"],
["少年リップルズ","BSC","1.8"],
["少年リップルズ","ADV","4.65"],
["少年リップルズ","EXT","8.45"],
["振動デザイア","BSC","2.85"],
["振動デザイア","ADV","4.45"],
["振動デザイア","EXT","7.8"],
["晴天Bon Voyage","BSC","3.0"],
["晴天Bon Voyage","ADV","5.85"],
["晴天Bon Voyage","EXT","8.85"],
["セツナトリップ","BSC","2.2"],
["セツナトリップ","ADV","3.8"],
["セツナトリップ","EXT","8.55"],
["戦場のタクトシュトック","BSC","4.05"],
["戦場のタクトシュトック","ADV","5.35"],
["戦場のタクトシュトック","EXT","8.25"],
["創世ノート","BSC","2.3"],
["創世ノート","ADV","6.2"],
["創世ノート","EXT","8.2"],
["ちくわパフェだよ☆CKP","BSC","3.6"],
["ちくわパフェだよ☆CKP","ADV","4.95"],
["ちくわパフェだよ☆CKP","EXT","7.65"],
["デストロイマーチ","BSC","1.0"],
["デストロイマーチ","ADV","3.8"],
["デストロイマーチ","EXT","7.75"],
["デッドボヲルdeホームラン","BSC","1.25"],
["デッドボヲルdeホームラン","ADV","3.85"],
["デッドボヲルdeホームラン","EXT","7.8"],
["轟け!恋のビーンボール!! ～96バット砲炸裂!GITADORAシリーズMVP弾!～","BSC","2.2"],
["轟け!恋のビーンボール!! ～96バット砲炸裂!GITADORAシリーズMVP弾!～","ADV","4.85"],
["轟け!恋のビーンボール!! ～96バット砲炸裂!GITADORAシリーズMVP弾!～","EXT","7.75"],
["ドリーム・キッス","BSC","1.6"],
["ドリーム・キッス","ADV","4.9"],
["ドリーム・キッス","EXT","6.4"],
["†渚の小悪魔ラヴリィ～レイディオ† (GITADORA ver.)","BSC","1.25"],
["†渚の小悪魔ラヴリィ～レイディオ† (GITADORA ver.)","ADV","4.45"],
["†渚の小悪魔ラヴリィ～レイディオ† (GITADORA ver.)","EXT","8.15"],
["虹色の花","BSC","2.75"],
["虹色の花","ADV","6.55"],
["虹色の花","EXT","8.7"],
["猫侍の逆襲","BSC","2.7"],
["猫侍の逆襲","ADV","5.3"],
["猫侍の逆襲","EXT","9.72"],
["ノンフィクションワールド","BSC","2.95"],
["ノンフィクションワールド","ADV","4.2"],
["ノンフィクションワールド","EXT","7.8"],
["羽根亡キ少女唄","BSC","2.6"],
["羽根亡キ少女唄","ADV","4.15"],
["羽根亡キ少女唄","EXT","8.1"],
["春待ち花","BSC","2.65"],
["春待ち花","ADV","5.4"],
["春待ち花","EXT","7.6"],
["白虎転生録","BSC","3.95"],
["白虎転生録","ADV","5.85"],
["白虎転生録","EXT","7.4"],
["白虎転生録","MAS","8.6"],
["ファッションモンスター","BSC","1.05"],
["ファッションモンスター","ADV","2.0"],
["ファッションモンスター","EXT","6.1"],
["冬色","BSC","2.45"],
["冬色","ADV","5.8"],
["冬色","EXT","8.55"],
["フレッフレー♪熱血チアガール","BSC","2.75"],
["フレッフレー♪熱血チアガール","ADV","6.0"],
["フレッフレー♪熱血チアガール","EXT","9.65"],
["放課後ストライド","BSC","3.15"],
["放課後ストライド","ADV","5.7"],
["放課後ストライド","EXT","8.0"],
["僕とサヨナラの合図","BSC","2.1"],
["僕とサヨナラの合図","ADV","3.95"],
["僕とサヨナラの合図","EXT","6.3"],
["ボクらのトリップデイズ","BSC","3.6"],
["ボクらのトリップデイズ","ADV","5.0"],
["ボクらのトリップデイズ","EXT","7.4"],
["ポップミュージック続論","BSC","2.85"],
["ポップミュージック続論","ADV","6.0"],
["ポップミュージック続論","EXT","7.85"],
["ホーンテッド★メイドランチ","BSC","2.5"],
["ホーンテッド★メイドランチ","ADV","5.9"],
["ホーンテッド★メイドランチ","EXT","8.65"],
["ボンビースキップ!!","BSC","3.35"],
["ボンビースキップ!!","ADV","6.45"],
["ボンビースキップ!!","EXT","8.6"],
["マインド・ゲーム","BSC","2.15"],
["マインド・ゲーム","ADV","4.9"],
["マインド・ゲーム","EXT","8.35"],
["マネマネサイコトロピック","BSC","3.35"],
["マネマネサイコトロピック","ADV","5.45"],
["マネマネサイコトロピック","EXT","8.25"],
["三毛猫ロックンロール","BSC","3.45"],
["三毛猫ロックンロール","ADV","6.2"],
["三毛猫ロックンロール","EXT","8.35"],
["見習い天使と星降りの丘","BSC","2.65"],
["見習い天使と星降りの丘","ADV","4.9"],
["見習い天使と星降りの丘","EXT","8.25"],
["見習い天使と星降りの丘","MAS","9.2"],
["めうめうぺったんたん!!","BSC","2.85"],
["めうめうぺったんたん!!","ADV","5.0"],
["めうめうぺったんたん!!","EXT","7.7"],
["女々しくて","BSC","1.45"],
["女々しくて","ADV","4.6"],
["女々しくて","EXT","6.35"],
["もぎたてANGEL","BSC","2.65"],
["もぎたてANGEL","ADV","4.5"],
["もぎたてANGEL","EXT","6.0"],
["野球の遊び方 そしてその歴史 ～決定版～","BSC","1.5"],
["野球の遊び方 そしてその歴史 ～決定版～","ADV","4.3"],
["野球の遊び方 そしてその歴史 ～決定版～","EXT","8.0"],
["夜咄ディセイブ","BSC","2.35"],
["夜咄ディセイブ","ADV","4.1"],
["夜咄ディセイブ","EXT","8.35"],
["雷君","BSC","2.9"],
["雷君","ADV","4.9"],
["雷君","EXT","8.7"],
["ラキラキ (GITADORA Ver.)","BSC","3.15"],
["ラキラキ (GITADORA Ver.)","ADV","6.4"],
["ラキラキ (GITADORA Ver.)","EXT","8.9"],
["量子の海のリントヴルム (GITADOROCK Ver.)","BSC","3.75"],
["量子の海のリントヴルム (GITADOROCK Ver.)","ADV","5.6"],
["量子の海のリントヴルム (GITADOROCK Ver.)","EXT","8.55"],
["ロックスターと魔法のランプ","BSC","1.15"],
["ロックスターと魔法のランプ","ADV","4.3"],
["ロックスターと魔法のランプ","EXT","5.65"],
["Cherry","BSC","3.5"],
["Cherry","ADV","5.7"],
["Cherry","EXT","8.0"],
["Cleopatrysm","BSC","1.85"],
["Cleopatrysm","ADV","5.95"],
["Cleopatrysm","EXT","8.95"],
["Colors","BSC","3.75"],
["Colors","ADV","4.85"],
["Colors","EXT","6.9"],
["Crystal Toybox","BSC","3.4"],
["Crystal Toybox","ADV","6.0"],
["Crystal Toybox","EXT","8.5"],
["DEATH BRINGER","BSC","4.45"],
["DEATH BRINGER","ADV","5.3"],
["DEATH BRINGER","EXT","7.95"],
["DEATH BRINGER","MAS","8.95"],
["heliodor","BSC","3.6"],
["heliodor","ADV","5.8"],
["heliodor","EXT","7.9"],
["heliodor","MAS","9.0"],
["HYDRA","BSC","2.25"],
["HYDRA","ADV","5.45"],
["HYDRA","EXT","8.1"],
["Idola","BSC","3.2"],
["Idola","ADV","5.8"],
["Idola","EXT","7.7"],
["Idola","MAS","9.25"],
["Insania","BSC","2.6"],
["Insania","ADV","5.7"],
["Insania","EXT","8.25"],
["jkパラダイス","BSC","2.7"],
["jkパラダイス","ADV","4.4"],
["jkパラダイス","EXT","7.25"],
["KHAMEN BREAK","BSC","1.65"],
["KHAMEN BREAK","ADV","5.25"],
["KHAMEN BREAK","EXT","8.55"],
["LEMON & SALT","BSC","3.65"],
["LEMON & SALT","ADV","6.15"],
["LEMON & SALT","EXT","8.75"],
["LEMON & SALT","MAS","9.92"],
["LIFE","BSC","2.1"],
["LIFE","ADV","5.35"],
["LIFE","EXT","7.65"],
["Limit Level","BSC","3.1"],
["Limit Level","ADV","4.45"],
["Limit Level","EXT","7.85"],
["Mambo Caribbean 5","BSC","3.65"],
["Mambo Caribbean 5","ADV","6.3"],
["Mambo Caribbean 5","EXT","7.95"],
["MODEL DD ULTIMATES","BSC","5.35"],
["MODEL DD ULTIMATES","ADV","8.15"],
["MODEL DD ULTIMATES","EXT","9.5"],
["MODEL DD ULTIMATES","MAS","9.97"],
["NAKED SCREAM","BSC","4.25"],
["NAKED SCREAM","ADV","5.8"],
["NAKED SCREAM","EXT","8.65"],
["Nature(GITADORA ver.)","BSC","3.95"],
["Nature(GITADORA ver.)","ADV","6.55"],
["Nature(GITADORA ver.)","EXT","7.85"],
["Nature(GITADORA ver.)","MAS","9.62"],
["Noli Me Tangere","BSC","4.45"],
["Noli Me Tangere","ADV","6.7"],
["Noli Me Tangere","EXT","8.75"],
["Noli Me Tangere","MAS","9.6"],
["Pray to the Earth","BSC","3.95"],
["Pray to the Earth","ADV","6.15"],
["Pray to the Earth","EXT","7.7"],
["Pray to the Earth","MAS","9.1"],
["Quarrel and Harmony","BSC","4.3"],
["Quarrel and Harmony","ADV","5.5"],
["Quarrel and Harmony","EXT","7.25"],
["Quarrel and Harmony","MAS","8.45"],
["rage against usual","BSC","2.6"],
["rage against usual","ADV","4.9"],
["rage against usual","EXT","8.0"],
["rage against usual","MAS","9.0"],
["Re:GENERATION","BSC","2.25"],
["Re:GENERATION","ADV","5.1"],
["Re:GENERATION","EXT","8.15"],
["Silver star","BSC","3.45"],
["Silver star","ADV","6.05"],
["Silver star","EXT","7.45"],
["Silver star","MAS","8.8"],
["Summer '64","BSC","3.85"],
["Summer '64","ADV","6.35"],
["Summer '64","EXT","8.7"],
["The ULTIMATES -Brightness-","BSC","3.35"],
["The ULTIMATES -Brightness-","ADV","5.2"],
["The ULTIMATES -Brightness-","EXT","7.8"],
["The ULTIMATES -Brightness-","MAS","8.9"],
["The ULTIMATES -Darkness-","BSC","4.9"],
["The ULTIMATES -Darkness-","ADV","7.25"],
["The ULTIMATES -Darkness-","EXT","9.05"],
["The ULTIMATES -Darkness-","MAS","9.57"],
["TOXIC VIBRATION","BSC","4.05"],
["TOXIC VIBRATION","ADV","5.3"],
["TOXIC VIBRATION","EXT","8.1"],
["TOXIC VIBRATION","MAS","9.0"],
["UNLIMITED FIRE","BSC","1.95"],
["UNLIMITED FIRE","ADV","3.85"],
["UNLIMITED FIRE","EXT","6.95"],
["War evasion","BSC","4.15"],
["War evasion","ADV","5.35"],
["War evasion","EXT","7.35"],
["War evasion","MAS","9.0"],
["あなたが思うより愛していた","BSC","3.2"],
["あなたが思うより愛していた","ADV","5.45"],
["あなたが思うより愛していた","EXT","7.0"],
["家出少年と迷子少女","BSC","1.1"],
["家出少年と迷子少女","ADV","3.8"],
["家出少年と迷子少女","EXT","8.45"],
["イブの時代っ！","BSC","2.45"],
["イブの時代っ！","ADV","5.75"],
["イブの時代っ！","EXT","7.4"],
["魚氷に上り 耀よひて","BSC","1.9"],
["魚氷に上り 耀よひて","ADV","4.25"],
["魚氷に上り 耀よひて","EXT","8.25"],
["御千手メディテーション","BSC","2.25"],
["御千手メディテーション","ADV","5.55"],
["御千手メディテーション","EXT","8.85"],
["乙女繚乱 舞い咲き誇れ","BSC","4.35"],
["乙女繚乱 舞い咲き誇れ","ADV","5.4"],
["乙女繚乱 舞い咲き誇れ","EXT","8.1"],
["温故知新でいこっ！","BSC","2.3"],
["温故知新でいこっ！","ADV","5.65"],
["温故知新でいこっ！","EXT","6.75"],
["凱歌の奏","BSC","3.45"],
["凱歌の奏","ADV","4.75"],
["凱歌の奏","EXT","8.7"],
["過食性:アイドル症候群","BSC","1.45"],
["過食性:アイドル症候群","ADV","2.95"],
["過食性:アイドル症候群","EXT","5.7"],
["過食性:アイドル症候群","MAS","7.9"],
["九尾狐夜行","BSC","4.5"],
["九尾狐夜行","ADV","5.65"],
["九尾狐夜行","EXT","8.3"],
["九尾狐夜行","MAS","9.1"],
["狂艶ノ華","BSC","3.9"],
["狂艶ノ華","ADV","5.7"],
["狂艶ノ華","EXT","8.2"],
["煌-灼熱の裁き-","BSC","2.4"],
["煌-灼熱の裁き-","ADV","5.9"],
["煌-灼熱の裁き-","EXT","8.1"],
["幻想系世界修復少女","BSC","2.25"],
["幻想系世界修復少女","ADV","5.4"],
["幻想系世界修復少女","EXT","7.55"],
["恋とキングコング","BSC","2.35"],
["恋とキングコング","ADV","4.8"],
["恋とキングコング","EXT","7.9"],
["虚空と光明のディスクール","BSC","2.2"],
["虚空と光明のディスクール","ADV","4.45"],
["虚空と光明のディスクール","EXT","6.35"],
["今宵フラクタル","BSC","3.35"],
["今宵フラクタル","ADV","5.65"],
["今宵フラクタル","EXT","7.8"],
["残酷な天使のテーゼ","BSC","1.25"],
["残酷な天使のテーゼ","ADV","3.5"],
["残酷な天使のテーゼ","EXT","4.95"],
["時雨インソムニア","BSC","2.9"],
["時雨インソムニア","ADV","4.45"],
["時雨インソムニア","EXT","7.65"],
["守護神","BSC","3.1"],
["守護神","ADV","5.3"],
["守護神","EXT","8.55"],
["ジュピターガンズノベル","BSC","4.9"],
["ジュピターガンズノベル","ADV","6.3"],
["ジュピターガンズノベル","EXT","8.1"],
["ジュピターガンズノベル","MAS","9.15"],
["相反オポチュニティー","BSC","2.9"],
["相反オポチュニティー","ADV","5.95"],
["相反オポチュニティー","EXT","8.7"],
["だから君じゃない。","BSC","3.0"],
["だから君じゃない。","ADV","4.75"],
["だから君じゃない。","EXT","7.2"],
["たまごの物理科学的 及び調理特性に関しての調査、そしてその考察","BSC","3.6"],
["たまごの物理科学的 及び調理特性に関しての調査、そしてその考察","ADV","4.75"],
["たまごの物理科学的 及び調理特性に関しての調査、そしてその考察","EXT","7.55"],
["たまごの物理科学的 及び調理特性に関しての調査、そしてその考察","MAS","9.15"],
["天地動伝説","BSC","4.0"],
["天地動伝説","ADV","5.9"],
["天地動伝説","EXT","7.95"],
["天地動伝説","MAS","9.7"],
["童話回廊","BSC","4.15"],
["童話回廊","ADV","5.95"],
["童話回廊","EXT","8.6"],
["童話回廊","MAS","9.62"],
["都会征服Girls☆","BSC","2.0"],
["都会征服Girls☆","ADV","4.75"],
["都会征服Girls☆","EXT","7.9"],
["とってもとっても、ありがとう。","BSC","2.0"],
["とってもとっても、ありがとう。","ADV","4.35"],
["とってもとっても、ありがとう。","EXT","6.2"],
["走れメロンパン","BSC","1.15"],
["走れメロンパン","ADV","4.1"],
["走れメロンパン","EXT","6.4"],
["果たし状","BSC","2.8"],
["果たし状","ADV","4.6"],
["果たし状","EXT","8.0"],
["バンブーソード・ガール","BSC","4.3"],
["バンブーソード・ガール","ADV","6.15"],
["バンブーソード・ガール","EXT","8.8"],
["バンブーソード・ガール","MAS","9.85"],
["一粒のナミダ","BSC","2.65"],
["一粒のナミダ","ADV","4.55"],
["一粒のナミダ","EXT","8.25"],
["星宿る空の下で","BSC","3.8"],
["星宿る空の下で","ADV","5.15"],
["星宿る空の下で","EXT","7.45"],
["星宿る空の下で","MAS","8.3"],
["ポップミュージック論","BSC","1.7"],
["ポップミュージック論","ADV","4.6"],
["ポップミュージック論","EXT","8.15"],
["滅びに至るエランプシス","BSC","2.95"],
["滅びに至るエランプシス","ADV","5.85"],
["滅びに至るエランプシス","EXT","8.25"],
["回レ！雪月花","BSC","1.6"],
["回レ！雪月花","ADV","4.65"],
["回レ！雪月花","EXT","7.75"],
["水鏡","BSC","2.15"],
["水鏡","ADV","5.45"],
["水鏡","EXT","8.35"],
["めた・メタ?ひまわり*パンチ -デモテープVer.-","BSC","2.25"],
["めた・メタ?ひまわり*パンチ -デモテープVer.-","ADV","4.5"],
["めた・メタ?ひまわり*パンチ -デモテープVer.-","EXT","6.5"],
["滅亡天使 † にこきゅっぴん","BSC","3.1"],
["滅亡天使 † にこきゅっぴん","ADV","6.1"],
["滅亡天使 † にこきゅっぴん","EXT","8.6"],
["幽明異境","BSC","3.75"],
["幽明異境","ADV","5.3"],
["幽明異境","EXT","7.65"],
["幽明異境","MAS","8.7"],
["凛として咲く花の如く ～ひなビタ♪ edition～","BSC","3.25"],
["凛として咲く花の如く ～ひなビタ♪ edition～","ADV","5.8"],
["凛として咲く花の如く ～ひなビタ♪ edition～","EXT","7.65"],
["凛として咲く花の如く ～ひなビタ♪ edition～","MAS","8.65"],
["3 A.M. ディテクティブ・ゲーム","BSC","1.85"],
["3 A.M. ディテクティブ・ゲーム","ADV","3.75"],
["3 A.M. ディテクティブ・ゲーム","EXT","6.1"],
["3 A.M. ディテクティブ・ゲーム","MAS","7.05"],
["Alternative Tactics, Second Urgent Issue","BSC","2.6"],
["Alternative Tactics, Second Urgent Issue","ADV","4.35"],
["Alternative Tactics, Second Urgent Issue","EXT","6.95"],
["Alternative Tactics, Second Urgent Issue","MAS","7.9"],
["Anathema","BSC","4.7"],
["Anathema","ADV","7.0"],
["Anathema","EXT","9.35"],
["Anathema","MAS","9.9"],
["Arx Tyranni","BSC","3.0"],
["Arx Tyranni","ADV","4.65"],
["Arx Tyranni","EXT","6.4"],
["Arx Tyranni","MAS","7.3"],
["BELLS","BSC","3.7"],
["BELLS","ADV","5.1"],
["BELLS","EXT","7.8"],
["BELLS","MAS","8.9"],
["Blaze","BSC","3.75"],
["Blaze","ADV","5.05"],
["Blaze","EXT","7.25"],
["Blaze","MAS","8.5"],
["Burning Cremation","BSC","3.6"],
["Burning Cremation","ADV","4.85"],
["Burning Cremation","EXT","7.4"],
["Burning Cremation","MAS","8.7"],
["Butterfly Effect","BSC","2.1"],
["Butterfly Effect","ADV","3.45"],
["Butterfly Effect","EXT","5.85"],
["Butterfly Effect","MAS","7.3"],
["Covered With The Wire","BSC","2.4"],
["Covered With The Wire","ADV","5.1"],
["Covered With The Wire","EXT","6.95"],
["Covered With The Wire","MAS","8.95"],
["Deep Deep Inside","BSC","1.75"],
["Deep Deep Inside","ADV","5.25"],
["Deep Deep Inside","EXT","7.0"],
["Deep Deep Inside","MAS","8.5"],
["DEMON SLAYER","BSC","4.05"],
["DEMON SLAYER","ADV","5.65"],
["DEMON SLAYER","EXT","7.45"],
["DEMON SLAYER","MAS","8.55"],
["Destiny Wings","BSC","2.6"],
["Destiny Wings","ADV","5.3"],
["Destiny Wings","EXT","7.35"],
["Destiny Wings","MAS","8.35"],
["double thrash","BSC","1.75"],
["double thrash","ADV","4.8"],
["double thrash","EXT","7.65"],
["double thrash","MAS","9.15"],
["Eisenplatte","BSC","3.95"],
["Eisenplatte","ADV","5.7"],
["Eisenplatte","EXT","7.75"],
["Eisenplatte","MAS","9.77"],
["EMPYREAL CATASTROPHE","BSC","2.3"],
["EMPYREAL CATASTROPHE","ADV","5.15"],
["EMPYREAL CATASTROPHE","EXT","7.8"],
["EMPYREAL CATASTROPHE","MAS","9.67"],
["escape","BSC","2.45"],
["escape","ADV","3.75"],
["escape","EXT","5.65"],
["escape","MAS","7.3"],
["EVIL OGRE","BSC","3.25"],
["EVIL OGRE","ADV","5.15"],
["EVIL OGRE","EXT","7.85"],
["EVIL OGRE","MAS","8.95"],
["FAIRY TALE","BSC","3.25"],
["FAIRY TALE","ADV","5.95"],
["FAIRY TALE","EXT","7.7"],
["FAIRY TALE","MAS","8.85"],
["Feed The Hunger","BSC","3.35"],
["Feed The Hunger","ADV","5.05"],
["Feed The Hunger","EXT","8.3"],
["Feed The Hunger","MAS","9.25"],
["Fire in my heart","BSC","3.2"],
["Fire in my heart","ADV","4.5"],
["Fire in my heart","EXT","5.8"],
["Fire in my heart","MAS","7.4"],
["Forever Young","BSC","2.75"],
["Forever Young","ADV","4.0"],
["Forever Young","EXT","6.65"],
["Forever Young","MAS","8.65"],
["For You","BSC","1.2"],
["For You","ADV","3.0"],
["For You","EXT","5.5"],
["For You","MAS","7.0"],
["Golden galaxy","BSC","3.75"],
["Golden galaxy","ADV","5.5"],
["Golden galaxy","EXT","7.85"],
["Golden galaxy","MAS","9.45"],
["Good bye, Summer～さよならは言わない～","BSC","1.35"],
["Good bye, Summer～さよならは言わない～","ADV","3.8"],
["Good bye, Summer～さよならは言わない～","EXT","5.5"],
["Good bye, Summer～さよならは言わない～","MAS","6.6"],
["GO READY","BSC","2.15"],
["GO READY","ADV","4.1"],
["GO READY","EXT","5.9"],
["GO READY","MAS","7.25"],
["Graphic Melody","BSC","2.75"],
["Graphic Melody","ADV","5.15"],
["Graphic Melody","EXT","7.4"],
["Graphic Melody","MAS","8.35"],
["HAPPY! LUCKY! SUNFLOWER!","BSC","2.75"],
["HAPPY! LUCKY! SUNFLOWER!","ADV","4.45"],
["HAPPY! LUCKY! SUNFLOWER!","EXT","6.15"],
["HAPPY! LUCKY! SUNFLOWER!","MAS","7.15"],
["In The Breeze","BSC","2.25"],
["In The Breeze","ADV","4.35"],
["In The Breeze","EXT","6.35"],
["In The Breeze","MAS","8.15"],
["Just Believe","BSC","2.1"],
["Just Believe","ADV","5.25"],
["Just Believe","EXT","7.55"],
["Just Believe","MAS","8.6"],
["Megatonic Shaper","BSC","3.2"],
["Megatonic Shaper","ADV","4.85"],
["Megatonic Shaper","EXT","6.95"],
["Megatonic Shaper","MAS","8.85"],
["MIND ERUPTION","BSC","3.7"],
["MIND ERUPTION","ADV","5.45"],
["MIND ERUPTION","EXT","7.8"],
["MIND ERUPTION","MAS","9.8"],
["MODEL DD11","BSC","5.0"],
["MODEL DD11","ADV","6.5"],
["MODEL DD11","EXT","9.1"],
["MODEL DD11","MAS","9.72"],
["My Way, My Life","BSC","3.2"],
["My Way, My Life","ADV","4.45"],
["My Way, My Life","EXT","6.35"],
["My Way, My Life","MAS","7.5"],
["neko*neko","BSC","2.25"],
["neko*neko","ADV","5.1"],
["neko*neko","EXT","6.95"],
["neko*neko","MAS","8.6"],
["No Reason of Fear","BSC","3.85"],
["No Reason of Fear","ADV","4.95"],
["No Reason of Fear","EXT","6.9"],
["No Reason of Fear","MAS","8.45"],
["Party People","BSC","2.85"],
["Party People","ADV","5.65"],
["Party People","EXT","7.2"],
["Party People","MAS","9.0"],
["Pretty Trying","BSC","2.25"],
["Pretty Trying","ADV","4.45"],
["Pretty Trying","EXT","6.3"],
["Pretty Trying","MAS","7.15"],
["RAINY DAYS","BSC","3.2"],
["RAINY DAYS","ADV","5.45"],
["RAINY DAYS","EXT","7.6"],
["RAINY DAYS","MAS","8.65"],
["ROZA DE ANDALUCIA","BSC","3.5"],
["ROZA DE ANDALUCIA","ADV","6.25"],
["ROZA DE ANDALUCIA","EXT","8.55"],
["ROZA DE ANDALUCIA","MAS","9.75"],
["Ruins","BSC","2.2"],
["Ruins","ADV","5.5"],
["Ruins","EXT","6.7"],
["Ruins","MAS","7.95"],
["Russian Caravan Rhapsody","BSC","2.6"],
["Russian Caravan Rhapsody","ADV","4.9"],
["Russian Caravan Rhapsody","EXT","7.55"],
["Russian Caravan Rhapsody","MAS","8.9"],
["Sand Blow","BSC","1.35"],
["Sand Blow","ADV","4.65"],
["Sand Blow","EXT","6.7"],
["Sand Blow","MAS","7.85"],
["SEASONS","BSC","2.35"],
["SEASONS","ADV","5.25"],
["SEASONS","EXT","6.95"],
["SEASONS","MAS","8.8"],
["Sense of the Scamper","BSC","1.95"],
["Sense of the Scamper","ADV","3.85"],
["Sense of the Scamper","EXT","5.95"],
["Sense of the Scamper","MAS","7.15"],
["Skyphobia","BSC","2.3"],
["Skyphobia","ADV","4.85"],
["Skyphobia","EXT","8.2"],
["Skyphobia","MAS","9.2"],
["Skyscraper","BSC","3.45"],
["Skyscraper","ADV","6.8"],
["Skyscraper","EXT","9.2"],
["Skyscraper","MAS","9.94"],
["STAND PROUD","BSC","2.9"],
["STAND PROUD","ADV","5.45"],
["STAND PROUD","EXT","6.85"],
["STAND PROUD","MAS","7.75"],
["Stellar Notes","BSC","3.6"],
["Stellar Notes","ADV","5.5"],
["Stellar Notes","EXT","7.2"],
["Stellar Notes","MAS","9.1"],
["Street For Student","BSC","2.0"],
["Street For Student","ADV","4.5"],
["Street For Student","EXT","7.8"],
["Street For Student","MAS","8.8"],
["Surge","BSC","2.15"],
["Surge","ADV","4.8"],
["Surge","EXT","6.9"],
["Surge","MAS","8.2"],
["Terra Car","BSC","3.35"],
["Terra Car","ADV","4.7"],
["Terra Car","EXT","8.15"],
["Terra Car","MAS","9.7"],
["The New Myth","BSC","4.35"],
["The New Myth","ADV","6.3"],
["The New Myth","EXT","7.8"],
["The New Myth","MAS","9.6"],
["The Town of Sunrise","BSC","2.65"],
["The Town of Sunrise","ADV","4.05"],
["The Town of Sunrise","EXT","6.1"],
["The Town of Sunrise","MAS","8.1"],
["Twilight","BSC","3.5"],
["Twilight","ADV","4.85"],
["Twilight","EXT","6.45"],
["Twilight","MAS","7.8"],
["Under The Nest -Remaster-","BSC","2.15"],
["Under The Nest -Remaster-","ADV","4.8"],
["Under The Nest -Remaster-","EXT","5.9"],
["Under The Nest -Remaster-","MAS","6.9"],
["WITCH HUNT","BSC","2.1"],
["WITCH HUNT","ADV","5.15"],
["WITCH HUNT","EXT","7.55"],
["WITCH HUNT","MAS","9.05"],
["wound","BSC","1.95"],
["wound","ADV","4.15"],
["wound","EXT","6.9"],
["wound","MAS","8.4"],
["青い月","BSC","1.95"],
["青い月","ADV","4.3"],
["青い月","EXT","6.15"],
["青い月","MAS","7.05"],
["明けぬ夜","BSC","2.3"],
["明けぬ夜","ADV","4.95"],
["明けぬ夜","EXT","6.7"],
["明けぬ夜","MAS","8.55"],
["朝顔ノ涙","BSC","1.8"],
["朝顔ノ涙","ADV","3.4"],
["朝顔ノ涙","EXT","6.75"],
["朝顔ノ涙","MAS","7.65"],
["あたしを○○してください","BSC","3.85"],
["あたしを○○してください","ADV","5.45"],
["あたしを○○してください","EXT","7.7"],
["あたしを○○してください","MAS","8.85"],
["在るが儘に","BSC","2.4"],
["在るが儘に","ADV","4.9"],
["在るが儘に","EXT","7.0"],
["在るが儘に","MAS","8.15"],
["アンモノクローム","BSC","2.45"],
["アンモノクローム","ADV","4.15"],
["アンモノクローム","EXT","6.5"],
["アンモノクローム","MAS","8.15"],
["怒りと共に去りぬ！！","BSC","1.95"],
["怒りと共に去りぬ！！","ADV","5.0"],
["怒りと共に去りぬ！！","EXT","6.8"],
["怒りと共に去りぬ！！","MAS","8.45"],
["異常震域","BSC","3.5"],
["異常震域","ADV","5.75"],
["異常震域","EXT","7.75"],
["異常震域","MAS","9.57"],
["いま 我々にできること","BSC","2.2"],
["いま 我々にできること","ADV","4.65"],
["いま 我々にできること","EXT","6.75"],
["いま 我々にできること","MAS","8.3"],
["彩","BSC","2.15"],
["彩","ADV","4.35"],
["彩","EXT","6.9"],
["彩","MAS","7.8"],
["エキサイティング!!も・ちゃ・ちゃ☆","BSC","4.2"],
["エキサイティング!!も・ちゃ・ちゃ☆","ADV","5.55"],
["エキサイティング!!も・ちゃ・ちゃ☆","EXT","7.7"],
["エキサイティング!!も・ちゃ・ちゃ☆","MAS","9.5"],
["垓","BSC","4.45"],
["垓","ADV","6.15"],
["垓","EXT","8.35"],
["垓","MAS","9.87"],
["カケラ","BSC","2.55"],
["カケラ","ADV","4.3"],
["カケラ","EXT","6.9"],
["カケラ","MAS","8.55"],
["完全無欠の無重力ダイブ","BSC","1.8"],
["完全無欠の無重力ダイブ","ADV","3.85"],
["完全無欠の無重力ダイブ","EXT","5.95"],
["完全無欠の無重力ダイブ","MAS","8.3"],
["狂鬼村正","BSC","2.7"],
["狂鬼村正","ADV","4.0"],
["狂鬼村正","EXT","6.9"],
["狂鬼村正","MAS","7.75"],
["鎖 ～KUSARI～","BSC","1.9"],
["鎖 ～KUSARI～","ADV","3.45"],
["鎖 ～KUSARI～","EXT","5.55"],
["鎖 ～KUSARI～","MAS","7.75"],
["グッバイジョニーA","BSC","1.9"],
["グッバイジョニーA","ADV","3.35"],
["グッバイジョニーA","EXT","5.95"],
["グッバイジョニーA","MAS","7.3"],
["紅蓮","BSC","2.9"],
["紅蓮","ADV","5.65"],
["紅蓮","EXT","7.4"],
["紅蓮","MAS","8.9"],
["黒髪乱れし修羅となりて～凛 edition～","BSC","2.9"],
["黒髪乱れし修羅となりて～凛 edition～","ADV","4.85"],
["黒髪乱れし修羅となりて～凛 edition～","EXT","6.6"],
["黒髪乱れし修羅となりて～凛 edition～","MAS","8.85"],
["京","BSC","3.25"],
["京","ADV","5.1"],
["京","EXT","7.15"],
["京","MAS","9.3"],
["激アツ☆マジヤバ☆チアガール","BSC","2.1"],
["激アツ☆マジヤバ☆チアガール","ADV","3.15"],
["激アツ☆マジヤバ☆チアガール","EXT","6.15"],
["激アツ☆マジヤバ☆チアガール","MAS","7.3"],
["激情ノ華ト散ルラン","BSC","2.7"],
["激情ノ華ト散ルラン","ADV","4.6"],
["激情ノ華ト散ルラン","EXT","6.7"],
["激情ノ華ト散ルラン","MAS","8.8"],
["恋する☆宇宙戦争っ!!(GITADOROCK ver.)","BSC","2.15"],
["恋する☆宇宙戦争っ!!(GITADOROCK ver.)","ADV","5.25"],
["恋する☆宇宙戦争っ!!(GITADOROCK ver.)","EXT","7.1"],
["恋する☆宇宙戦争っ!!(GITADOROCK ver.)","MAS","8.0"],
["恋のミラクルレシピ","BSC","2.95"],
["恋のミラクルレシピ","ADV","5.25"],
["恋のミラクルレシピ","EXT","6.9"],
["恋のミラクルレシピ","MAS","8.55"],
["サイレンサイン","BSC","2.25"],
["サイレンサイン","ADV","4.95"],
["サイレンサイン","EXT","7.15"],
["サイレンサイン","MAS","8.8"],
["サヨナラ・ヘヴン -GITADOROCK ver.-","BSC","2.75"],
["サヨナラ・ヘヴン -GITADOROCK ver.-","ADV","4.85"],
["サヨナラ・ヘヴン -GITADOROCK ver.-","EXT","8.25"],
["サヨナラ・ヘヴン -GITADOROCK ver.-","MAS","9.1"],
["漆黒のスペシャルプリンセスサンデー","BSC","2.7"],
["漆黒のスペシャルプリンセスサンデー","ADV","4.7"],
["漆黒のスペシャルプリンセスサンデー","EXT","7.15"],
["漆黒のスペシャルプリンセスサンデー","MAS","8.65"],
["ジャガー人間の受難","BSC","4.0"],
["ジャガー人間の受難","ADV","6.7"],
["ジャガー人間の受難","EXT","8.4"],
["ジャガー人間の受難","MAS","8.95"],
["終極","BSC","3.2"],
["終極","ADV","4.45"],
["終極","EXT","6.3"],
["終極","MAS","7.65"],
["真摯撃情マイペース","BSC","3.0"],
["真摯撃情マイペース","ADV","4.75"],
["真摯撃情マイペース","EXT","6.35"],
["真摯撃情マイペース","MAS","7.65"],
["水月鏡花のコノテーション","BSC","3.05"],
["水月鏡花のコノテーション","ADV","4.9"],
["水月鏡花のコノテーション","EXT","7.65"],
["水月鏡花のコノテーション","MAS","8.7"],
["スカイダイバー","BSC","2.0"],
["スカイダイバー","ADV","3.9"],
["スカイダイバー","EXT","6.2"],
["スカイダイバー","MAS","7.5"],
["零の位相","BSC","2.3"],
["零の位相","ADV","4.6"],
["零の位相","EXT","6.85"],
["零の位相","MAS","7.7"],
["全力バタンキュー","BSC","1.25"],
["全力バタンキュー","ADV","2.65"],
["全力バタンキュー","EXT","4.65"],
["全力バタンキュー","MAS","6.35"],
["葬送のエウロパ","BSC","4.3"],
["葬送のエウロパ","ADV","6.2"],
["葬送のエウロパ","EXT","8.15"],
["葬送のエウロパ","MAS","9.2"],
["太陽の子","BSC","3.8"],
["太陽の子","ADV","5.2"],
["太陽の子","EXT","8.35"],
["太陽の子","MAS","9.25"],
["遊戯大熊猫","BSC","4.95"],
["遊戯大熊猫","ADV","6.3"],
["遊戯大熊猫","EXT","7.65"],
["遊戯大熊猫","MAS","8.75"],
["地方創生☆チクワクティクス","BSC","2.9"],
["地方創生☆チクワクティクス","ADV","4.15"],
["地方創生☆チクワクティクス","EXT","6.85"],
["地方創生☆チクワクティクス","MAS","7.85"],
["超獣戯画","BSC","3.0"],
["超獣戯画","ADV","4.9"],
["超獣戯画","EXT","7.05"],
["超獣戯画","MAS","7.95"],
["追想 -SHINY DAYS-","BSC","1.95"],
["追想 -SHINY DAYS-","ADV","3.15"],
["追想 -SHINY DAYS-","EXT","6.15"],
["追想 -SHINY DAYS-","MAS","7.1"],
["天穹鳥-TEN・KYU・CHO-","BSC","1.65"],
["天穹鳥-TEN・KYU・CHO-","ADV","4.55"],
["天穹鳥-TEN・KYU・CHO-","EXT","6.55"],
["天穹鳥-TEN・KYU・CHO-","MAS","8.95"],
["天国ミュージック","BSC","1.9"],
["天国ミュージック","ADV","4.3"],
["天国ミュージック","EXT","6.4"],
["天国ミュージック","MAS","8.15"],
["透明はまだらに世界を告げて","BSC","2.9"],
["透明はまだらに世界を告げて","ADV","4.85"],
["透明はまだらに世界を告げて","EXT","6.95"],
["透明はまだらに世界を告げて","MAS","8.9"],
["どきドキ バレンタイン","BSC","2.05"],
["どきドキ バレンタイン","ADV","3.4"],
["どきドキ バレンタイン","EXT","5.9"],
["どきドキ バレンタイン","MAS","7.3"],
["時の妖花","BSC","2.55"],
["時の妖花","ADV","5.45"],
["時の妖花","EXT","7.3"],
["時の妖花","MAS","8.95"],
["とびっきりのふわっふわ","BSC","1.35"],
["とびっきりのふわっふわ","ADV","3.6"],
["とびっきりのふわっふわ","EXT","6.15"],
["とびっきりのふわっふわ","MAS","7.55"],
["夏色DIARY -GITADORA style-","BSC","2.0"],
["夏色DIARY -GITADORA style-","ADV","4.35"],
["夏色DIARY -GITADORA style-","EXT","6.55"],
["夏色DIARY -GITADORA style-","MAS","7.65"],
["虹色遊園地","BSC","2.65"],
["虹色遊園地","ADV","4.6"],
["虹色遊園地","EXT","7.0"],
["虹色遊園地","MAS","8.8"],
["箱庭の世界","BSC","1.55"],
["箱庭の世界","ADV","2.6"],
["箱庭の世界","EXT","4.05"],
["箱庭の世界","MAS","6.0"],
["はなまるぴっぴはよいこだけ","BSC","1.6"],
["はなまるぴっぴはよいこだけ","ADV","3.7"],
["はなまるぴっぴはよいこだけ","EXT","5.4"],
["はなまるぴっぴはよいこだけ","MAS","7.45"],
["ファントムベロニカ","BSC","2.95"],
["ファントムベロニカ","ADV","5.15"],
["ファントムベロニカ","EXT","6.65"],
["ファントムベロニカ","MAS","8.0"],
["ブラックホール","BSC","2.3"],
["ブラックホール","ADV","4.25"],
["ブラックホール","EXT","7.55"],
["ブラックホール","MAS","8.4"],
["フラッター現象の顛末と単一指向性の感情論","BSC","3.45"],
["フラッター現象の顛末と単一指向性の感情論","ADV","4.35"],
["フラッター現象の顛末と単一指向性の感情論","EXT","6.35"],
["フラッター現象の顛末と単一指向性の感情論","MAS","7.7"],
["ブランコ","BSC","2.15"],
["ブランコ","ADV","4.45"],
["ブランコ","EXT","6.3"],
["ブランコ","MAS","7.6"],
["ほおずき程度には赤い頭髪","BSC","2.4"],
["ほおずき程度には赤い頭髪","ADV","4.85"],
["ほおずき程度には赤い頭髪","EXT","8.2"],
["ほおずき程度には赤い頭髪","MAS","9.0"],
["ぽかぽかレトロード","BSC","2.85"],
["ぽかぽかレトロード","ADV","5.15"],
["ぽかぽかレトロード","EXT","6.6"],
["ぽかぽかレトロード","MAS","8.45"],
["僕ガ壊レル前ニ","BSC","3.0"],
["僕ガ壊レル前ニ","ADV","5.2"],
["僕ガ壊レル前ニ","EXT","6.85"],
["僕ガ壊レル前ニ","MAS","8.75"],
["炎のDiargos","BSC","3.1"],
["炎のDiargos","ADV","5.25"],
["炎のDiargos","EXT","6.7"],
["炎のDiargos","MAS","8.3"],
["水面静かに大地の烈日わたらせて -Remaster-","BSC","3.8"],
["水面静かに大地の烈日わたらせて -Remaster-","ADV","5.4"],
["水面静かに大地の烈日わたらせて -Remaster-","EXT","7.15"],
["水面静かに大地の烈日わたらせて -Remaster-","MAS","8.45"],
["メギツネ","BSC","3.25"],
["メギツネ","ADV","5.55"],
["メギツネ","EXT","7.1"],
["メギツネ","MAS","8.2"],
["めた・メタ?ひまわり*パンチ","BSC","2.3"],
["めた・メタ?ひまわり*パンチ","ADV","4.25"],
["めた・メタ?ひまわり*パンチ","EXT","6.05"],
["めた・メタ?ひまわり*パンチ","MAS","7.5"],
["モフモフしたいの","BSC","4.05"],
["モフモフしたいの","ADV","6.0"],
["モフモフしたいの","EXT","8.75"],
["モフモフしたいの","MAS","9.92"],
["悠久のPEGASUS","BSC","2.85"],
["悠久のPEGASUS","ADV","5.55"],
["悠久のPEGASUS","EXT","8.2"],
["悠久のPEGASUS","MAS","9.9"],
["夕星の芒野と消ゆ","BSC","2.95"],
["夕星の芒野と消ゆ","ADV","4.3"],
["夕星の芒野と消ゆ","EXT","5.9"],
["夕星の芒野と消ゆ","MAS","7.45"],
["ユグドラシルの欠片","BSC","2.6"],
["ユグドラシルの欠片","ADV","3.85"],
["ユグドラシルの欠片","EXT","6.0"],
["ユグドラシルの欠片","MAS","7.35"],
["ラキ☆ハピDAYS!","BSC","2.95"],
["ラキ☆ハピDAYS!","ADV","4.6"],
["ラキ☆ハピDAYS!","EXT","6.0"],
["ラキ☆ハピDAYS!","MAS","8.1"],
["ラジカル少女","BSC","2.2"],
["ラジカル少女","ADV","4.05"],
["ラジカル少女","EXT","6.75"],
["ラジカル少女","MAS","8.0"],
["ララバイ哀愁","BSC","1.95"],
["ララバイ哀愁","ADV","3.45"],
["ララバイ哀愁","EXT","5.3"],
["ララバイ哀愁","MAS","6.6"],
["六花にくちづけ","BSC","2.45"],
["六花にくちづけ","ADV","4.8"],
["六花にくちづけ","EXT","7.35"],
["六花にくちづけ","MAS","8.3"],
["輪廻転生","BSC","3.8"],
["輪廻転生","ADV","5.0"],
["輪廻転生","EXT","7.75"],
["輪廻転生","MAS","9.25"],
["3dim","BSC","2.4"],
["3dim","ADV","4.35"],
["3dim","EXT","6.5"],
["3dim","MAS","8.8"],
["And The Dead Ravened For","BSC","2.0"],
["And The Dead Ravened For","ADV","4.1"],
["And The Dead Ravened For","EXT","6.5"],
["And The Dead Ravened For","MAS","8.3"],
["Ater Regis -Alius-","BSC","2.9"],
["Ater Regis -Alius-","ADV","5.0"],
["Ater Regis -Alius-","EXT","7.6"],
["Ater Regis -Alius-","MAS","8.6"],
["BAD HERO","BSC","2.45"],
["BAD HERO","ADV","3.9"],
["BAD HERO","EXT","6.7"],
["BAD HERO","MAS","8.35"],
["Beyond the light","BSC","3.7"],
["Beyond the light","ADV","5.05"],
["Beyond the light","EXT","6.9"],
["Beyond the light","MAS","7.85"],
["BLACK ROSES","BSC","4.6"],
["BLACK ROSES","ADV","7.05"],
["BLACK ROSES","EXT","9.1"],
["BLACK ROSES","MAS","9.85"],
["Blaze line","BSC","2.4"],
["Blaze line","ADV","4.1"],
["Blaze line","EXT","6.15"],
["Blaze line","MAS","7.4"],
["Ding Dong Bell","BSC","1.35"],
["Ding Dong Bell","ADV","3.5"],
["Ding Dong Bell","EXT","5.65"],
["Ding Dong Bell","MAS","7.0"],
["Drastic Your Dream","BSC","1.9"],
["Drastic Your Dream","ADV","4.0"],
["Drastic Your Dream","EXT","6.05"],
["Drastic Your Dream","MAS","7.75"],
["Dreamer's High","BSC","2.15"],
["Dreamer's High","ADV","4.2"],
["Dreamer's High","EXT","5.85"],
["Dreamer's High","MAS","7.2"],
["Durian","BSC","4.0"],
["Durian","ADV","6.05"],
["Durian","EXT","7.7"],
["Durian","MAS","9.45"],
["Exclamation","BSC","3.65"],
["Exclamation","ADV","5.15"],
["Exclamation","EXT","7.75"],
["Exclamation","MAS","9.15"],
["Fatal Attraction","BSC","3.75"],
["Fatal Attraction","ADV","5.55"],
["Fatal Attraction","EXT","7.1"],
["Fatal Attraction","MAS","8.4"],
["Fly far bounce","BSC","1.85"],
["Fly far bounce","ADV","5.15"],
["Fly far bounce","EXT","7.35"],
["Fly far bounce","MAS","8.55"],
["Get Money","BSC","1.25"],
["Get Money","ADV","3.95"],
["Get Money","EXT","5.7"],
["Get Money","MAS","6.5"],
["GO! GO! MANIAC","BSC","2.0"],
["GO! GO! MANIAC","ADV","3.8"],
["GO! GO! MANIAC","EXT","7.2"],
["GO! GO! MANIAC","MAS","8.95"],
["Hello","BSC","1.4"],
["Hello","ADV","2.9"],
["Hello","EXT","4.75"],
["Hello","MAS","6.3"],
["KING G (2017Mix)","BSC","2.5"],
["KING G (2017Mix)","ADV","4.5"],
["KING G (2017Mix)","EXT","6.45"],
["KING G (2017Mix)","MAS","7.7"],
["LIGHTNING","BSC","2.0"],
["LIGHTNING","ADV","4.25"],
["LIGHTNING","EXT","6.65"],
["LIGHTNING","MAS","8.0"],
["M1917","BSC","2.45"],
["M1917","ADV","5.5"],
["M1917","EXT","7.05"],
["M1917","MAS","8.6"],
["MEDUSA","BSC","4.45"],
["MEDUSA","ADV","6.25"],
["MEDUSA","EXT","7.35"],
["MEDUSA","MAS","8.7"],
["Misty Lake","BSC","1.95"],
["Misty Lake","ADV","3.5"],
["Misty Lake","EXT","5.25"],
["Misty Lake","MAS","6.3"],
["Monochrome Ortensia","BSC","2.5"],
["Monochrome Ortensia","ADV","4.0"],
["Monochrome Ortensia","EXT","6.4"],
["Monochrome Ortensia","MAS","7.85"],
["NO MORE SORROW","BSC","1.6"],
["NO MORE SORROW","ADV","3.85"],
["NO MORE SORROW","EXT","6.65"],
["NO MORE SORROW","MAS","8.3"],
["Our Faith (Faithful MTL Remix)","BSC","1.05"],
["Our Faith (Faithful MTL Remix)","ADV","4.35"],
["Our Faith (Faithful MTL Remix)","EXT","6.55"],
["Our Faith (Faithful MTL Remix)","MAS","8.65"],
["RAISE MY SWORD","BSC","2.35"],
["RAISE MY SWORD","ADV","5.0"],
["RAISE MY SWORD","EXT","7.55"],
["RAISE MY SWORD","MAS","8.85"],
["Raspberry","BSC","3.35"],
["Raspberry","ADV","5.3"],
["Raspberry","EXT","7.2"],
["Raspberry","MAS","8.6"],
["REFLEXES MANIPULATION","BSC","3.6"],
["REFLEXES MANIPULATION","ADV","5.5"],
["REFLEXES MANIPULATION","EXT","8.15"],
["REFLEXES MANIPULATION","MAS","9.85"],
["The Fourth Interval","BSC","3.35"],
["The Fourth Interval","ADV","4.95"],
["The Fourth Interval","EXT","6.3"],
["The Fourth Interval","MAS","8.5"],
["UNDER THE SUN","BSC","3.5"],
["UNDER THE SUN","ADV","4.8"],
["UNDER THE SUN","EXT","6.85"],
["UNDER THE SUN","MAS","7.75"],
["We Go Down","BSC","2.85"],
["We Go Down","ADV","5.65"],
["We Go Down","EXT","6.85"],
["We Go Down","MAS","8.75"],
["White Forest","BSC","3.9"],
["White Forest","ADV","6.85"],
["White Forest","EXT","8.95"],
["White Forest","MAS","9.9"],
["アンタレス","BSC","1.6"],
["アンタレス","ADV","3.85"],
["アンタレス","EXT","5.8"],
["アンタレス","MAS","7.85"],
["色ハニホヘト散リヌルヲ","BSC","1.85"],
["色ハニホヘト散リヌルヲ","ADV","3.75"],
["色ハニホヘト散リヌルヲ","EXT","5.8"],
["色ハニホヘト散リヌルヲ","MAS","7.15"],
["海の声","BSC","1.4"],
["海の声","ADV","2.9"],
["海の声","EXT","4.45"],
["海の声","MAS","6.1"],
["朧","BSC","1.35"],
["朧","ADV","3.75"],
["朧","EXT","6.35"],
["朧","MAS","8.8"],
["傷だらけの硝子","BSC","1.35"],
["傷だらけの硝子","ADV","3.55"],
["傷だらけの硝子","EXT","5.7"],
["傷だらけの硝子","MAS","7.95"],
["ギタドラシカ","BSC","4.05"],
["ギタドラシカ","ADV","5.8"],
["ギタドラシカ","EXT","7.55"],
["ギタドラシカ","MAS","9.05"],
["ギミチョコ！！","BSC","2.4"],
["ギミチョコ！！","ADV","3.95"],
["ギミチョコ！！","EXT","6.0"],
["ギミチョコ！！","MAS","6.95"],
["グローイングローイン","BSC","1.35"],
["グローイングローイン","ADV","3.5"],
["グローイングローイン","EXT","5.2"],
["グローイングローイン","MAS","7.0"],
["航海 ～ Seven Colors ～","BSC","2.4"],
["航海 ～ Seven Colors ～","ADV","4.7"],
["航海 ～ Seven Colors ～","EXT","6.15"],
["航海 ～ Seven Colors ～","MAS","7.6"],
["シュガーソングとビターステップ","BSC","1.7"],
["シュガーソングとビターステップ","ADV","4.05"],
["シュガーソングとビターステップ","EXT","5.65"],
["シュガーソングとビターステップ","MAS","7.1"],
["主亡き機械人形のまなざし","BSC","3.65"],
["主亡き機械人形のまなざし","ADV","5.35"],
["主亡き機械人形のまなざし","EXT","7.2"],
["主亡き機械人形のまなざし","MAS","9.1"],
["準備運動","BSC","2.95"],
["準備運動","ADV","5.35"],
["準備運動","EXT","7.35"],
["準備運動","MAS","8.85"],
["刹那","BSC","2.15"],
["刹那","ADV","4.6"],
["刹那","EXT","6.6"],
["刹那","MAS","8.4"],
["タンポポ","BSC","2.5"],
["タンポポ","ADV","4.6"],
["タンポポ","EXT","6.9"],
["タンポポ","MAS","8.95"],
["つまり･･･Gブルース!","BSC","2.45"],
["つまり･･･Gブルース!","ADV","4.3"],
["つまり･･･Gブルース!","EXT","5.95"],
["つまり･･･Gブルース!","MAS","7.7"],
["背水之陣","BSC","2.4"],
["背水之陣","ADV","4.8"],
["背水之陣","EXT","6.6"],
["背水之陣","MAS","9.05"],
["拍子迷宮","BSC","2.35"],
["拍子迷宮","ADV","4.75"],
["拍子迷宮","EXT","6.3"],
["拍子迷宮","MAS","8.9"],
["瑞鳥","BSC","2.15"],
["瑞鳥","ADV","4.5"],
["瑞鳥","EXT","7.0"],
["瑞鳥","MAS","8.95"],
["†闇鍋☆ROCK†","BSC","3.35"],
["†闇鍋☆ROCK†","ADV","5.8"],
["†闇鍋☆ROCK†","EXT","7.95"],
["†闇鍋☆ROCK†","MAS","9.2"],
["7th Floor","BSC","3.25"],
["7th Floor","ADV","5.35"],
["7th Floor","EXT","7.0"],
["7th Floor","MAS","8.25"],
["Aion","BSC","4.6"],
["Aion","ADV","6.1"],
["Aion","EXT","8.3"],
["Aion","MAS","9.6"],
["Be a Hero!","BSC","4.35"],
["Be a Hero!","ADV","6.15"],
["Be a Hero!","EXT","8.15"],
["Be a Hero!","MAS","9.05"],
["Beginning","BSC","3.05"],
["Beginning","ADV","5.4"],
["Beginning","EXT","7.6"],
["Beginning","MAS","9.05"],
["BLOOD RED","BSC","2.75"],
["BLOOD RED","ADV","4.4"],
["BLOOD RED","EXT","5.95"],
["BLOOD RED","MAS","7.75"],
["busy come, busy go!!","BSC","3.65"],
["busy come, busy go!!","ADV","5.45"],
["busy come, busy go!!","EXT","6.8"],
["busy come, busy go!!","MAS","8.4"],
["Cagayake!GIRLS","BSC","1.4"],
["Cagayake!GIRLS","ADV","3.75"],
["Cagayake!GIRLS","EXT","6.45"],
["Cagayake!GIRLS","MAS","7.85"],
["CALLME","BSC","3.5"],
["CALLME","ADV","5.55"],
["CALLME","EXT","6.8"],
["CALLME","MAS","8.35"],
["CAPTURING XANADU","BSC","5.0"],
["CAPTURING XANADU","ADV","6.4"],
["CAPTURING XANADU","EXT","8.3"],
["CAPTURING XANADU","MAS","9.82"],
["Cinnamon","BSC","4.5"],
["Cinnamon","ADV","6.55"],
["Cinnamon","EXT","8.7"],
["Cinnamon","MAS","9.65"],
["Clattanoia","BSC","2.2"],
["Clattanoia","ADV","4.15"],
["Clattanoia","EXT","5.8"],
["Clattanoia","MAS","7.5"],
["CQCQ","BSC","2.1"],
["CQCQ","ADV","4.05"],
["CQCQ","EXT","6.0"],
["CQCQ","MAS","7.45"],
["DREAMING-ING!!","BSC","1.75"],
["DREAMING-ING!!","ADV","3.6"],
["DREAMING-ING!!","EXT","5.05"],
["DREAMING-ING!!","MAS","6.35"],
["Drizzly Venom","BSC","2.1"],
["Drizzly Venom","ADV","4.1"],
["Drizzly Venom","EXT","6.35"],
["Drizzly Venom","MAS","8.25"],
["Duella Lyrica","BSC","3.55"],
["Duella Lyrica","ADV","5.7"],
["Duella Lyrica","EXT","7.65"],
["Duella Lyrica","MAS","8.7"],
["Fate of the Furious","BSC","4.35"],
["Fate of the Furious","ADV","6.3"],
["Fate of the Furious","EXT","7.95"],
["Fate of the Furious","MAS","9.7"],
["Fly to Sky","BSC","2.25"],
["Fly to Sky","ADV","5.1"],
["Fly to Sky","EXT","7.15"],
["Fly to Sky","MAS","8.3"],
["Killing Bites","BSC","2.35"],
["Killing Bites","ADV","4.35"],
["Killing Bites","EXT","7.0"],
["Killing Bites","MAS","9.2"],
["Life goes on","BSC","2.85"],
["Life goes on","ADV","4.7"],
["Life goes on","EXT","6.45"],
["Life goes on","MAS","7.8"],
["Life is beautiful","BSC","3.4"],
["Life is beautiful","ADV","5.35"],
["Life is beautiful","EXT","7.3"],
["Life is beautiful","MAS","9.65"],
["LIPS NOISE HUNTER","BSC","3.0"],
["LIPS NOISE HUNTER","ADV","5.05"],
["LIPS NOISE HUNTER","EXT","7.4"],
["LIPS NOISE HUNTER","MAS","9.05"],
["MODEL FT4","BSC","4.5"],
["MODEL FT4","ADV","6.45"],
["MODEL FT4","EXT","8.7"],
["MODEL FT4","MAS","9.9"],
["MONOLITH -GITADOROCK ver.-","BSC","2.6"],
["MONOLITH -GITADOROCK ver.-","ADV","4.2"],
["MONOLITH -GITADOROCK ver.-","EXT","6.65"],
["MONOLITH -GITADOROCK ver.-","MAS","8.75"],
["Navy blue sea","BSC","3.4"],
["Navy blue sea","ADV","5.45"],
["Navy blue sea","EXT","6.9"],
["Navy blue sea","MAS","8.45"],
["Nex:us","BSC","1.6"],
["Nex:us","ADV","5.2"],
["Nex:us","EXT","6.95"],
["Nex:us","MAS","8.2"],
["Next FUTURE","BSC","3.9"],
["Next FUTURE","ADV","5.4"],
["Next FUTURE","EXT","6.6"],
["Next FUTURE","MAS","7.45"],
["ONE DAY","BSC","3.3"],
["ONE DAY","ADV","4.6"],
["ONE DAY","EXT","6.35"],
["ONE DAY","MAS","7.55"],
["Perfect World","BSC","2.4"],
["Perfect World","ADV","6.1"],
["Perfect World","EXT","8.2"],
["Perfect World","MAS","9.05"],
["Physical Decay","BSC","4.45"],
["Physical Decay","ADV","6.1"],
["Physical Decay","EXT","7.45"],
["Physical Decay","MAS","9.25"],
["PIRATES BANQUET","BSC","4.15"],
["PIRATES BANQUET","ADV","6.5"],
["PIRATES BANQUET","EXT","9.0"],
["PIRATES BANQUET","MAS","9.87"],
["Pirates of Upas","BSC","3.15"],
["Pirates of Upas","ADV","5.85"],
["Pirates of Upas","EXT","7.35"],
["Pirates of Upas","MAS","8.45"],
["Prey","BSC","3.7"],
["Prey","ADV","6.05"],
["Prey","EXT","7.45"],
["Prey","MAS","8.75"],
["Puberty Dysthymia","BSC","3.9"],
["Puberty Dysthymia","ADV","6.3"],
["Puberty Dysthymia","EXT","8.15"],
["Puberty Dysthymia","MAS","9.75"],
["RAIN DROPS","BSC","2.45"],
["RAIN DROPS","ADV","4.5"],
["RAIN DROPS","EXT","6.45"],
["RAIN DROPS","MAS","8.0"],
["REBORN","BSC","2.8"],
["REBORN","ADV","4.9"],
["REBORN","EXT","6.9"],
["REBORN","MAS","8.75"],
["Rejoin","BSC","2.7"],
["Rejoin","ADV","5.25"],
["Rejoin","EXT","7.2"],
["Rejoin","MAS","8.25"],
["Sacrifice","BSC","3.4"],
["Sacrifice","ADV","5.3"],
["Sacrifice","EXT","7.6"],
["Sacrifice","MAS","9.55"],
["STAY TUNE","BSC","1.0"],
["STAY TUNE","ADV","3.75"],
["STAY TUNE","EXT","5.3"],
["STAY TUNE","MAS","6.5"],
["SUPER SUMMER SALE","BSC","3.25"],
["SUPER SUMMER SALE","ADV","5.2"],
["SUPER SUMMER SALE","EXT","6.2"],
["SUPER SUMMER SALE","MAS","8.4"],
["Sweet feelin'","BSC","2.9"],
["Sweet feelin'","ADV","4.85"],
["Sweet feelin'","EXT","6.9"],
["Sweet feelin'","MAS","8.55"],
["The Kingsroad","BSC","3.35"],
["The Kingsroad","ADV","5.5"],
["The Kingsroad","EXT","7.0"],
["The Kingsroad","MAS","9.0"],
["triangulum","BSC","4.2"],
["triangulum","ADV","6.45"],
["triangulum","EXT","8.3"],
["triangulum","MAS","9.91"],
["TRIPLE ORBIT","BSC","3.8"],
["TRIPLE ORBIT","ADV","4.9"],
["TRIPLE ORBIT","EXT","7.6"],
["TRIPLE ORBIT","MAS","8.85"],
["Victoria","BSC","3.75"],
["Victoria","ADV","5.85"],
["Victoria","EXT","7.4"],
["Victoria","MAS","8.85"],
["Windy Fairy -GITADO ROCK ver.-","BSC","3.2"],
["Windy Fairy -GITADO ROCK ver.-","ADV","5.9"],
["Windy Fairy -GITADO ROCK ver.-","EXT","7.45"],
["Windy Fairy -GITADO ROCK ver.-","MAS","8.35"],
["XIII","BSC","2.95"],
["XIII","ADV","4.75"],
["XIII","EXT","7.35"],
["XIII","MAS","9.45"],
["明日へと続く物語","BSC","2.1"],
["明日へと続く物語","ADV","4.5"],
["明日へと続く物語","EXT","6.6"],
["明日へと続く物語","MAS","8.25"],
["嘘だらけの僕から出た言葉","BSC","3.2"],
["嘘だらけの僕から出た言葉","ADV","4.6"],
["嘘だらけの僕から出た言葉","EXT","5.95"],
["嘘だらけの僕から出た言葉","MAS","7.75"],
["解読不能","BSC","2.2"],
["解読不能","ADV","4.3"],
["解読不能","EXT","6.2"],
["解読不能","MAS","7.65"],
["幾何学的『トリックスター』","BSC","3.9"],
["幾何学的『トリックスター』","ADV","5.5"],
["幾何学的『トリックスター』","EXT","6.8"],
["幾何学的『トリックスター』","MAS","8.3"],
["ギタドライト","BSC","2.2"],
["ギタドライト","ADV","4.8"],
["ギタドライト","EXT","6.0"],
["ギタドライト","MAS","7.6"],
["君と野獣","BSC","1.85"],
["君と野獣","ADV","3.7"],
["君と野獣","EXT","5.75"],
["君と野獣","MAS","6.8"],
["君も天真爛漫","BSC","2.6"],
["君も天真爛漫","ADV","3.95"],
["君も天真爛漫","EXT","5.45"],
["君も天真爛漫","MAS","6.85"],
["キリステゴメン","BSC","3.05"],
["キリステゴメン","ADV","5.8"],
["キリステゴメン","EXT","7.1"],
["キリステゴメン","MAS","8.8"],
["桐一葉","BSC","2.4"],
["桐一葉","ADV","3.9"],
["桐一葉","EXT","5.9"],
["桐一葉","MAS","8.1"],
["君氏危うくも近うよれ","BSC","2.2"],
["君氏危うくも近うよれ","ADV","4.5"],
["君氏危うくも近うよれ","EXT","6.2"],
["君氏危うくも近うよれ","MAS","7.45"],
["けもののおうじゃ★めうめう","BSC","3.0"],
["けもののおうじゃ★めうめう","ADV","5.3"],
["けもののおうじゃ★めうめう","EXT","6.65"],
["けもののおうじゃ★めうめう","MAS","8.2"],
["最強ゲームエンド","BSC","3.2"],
["最強ゲームエンド","ADV","5.15"],
["最強ゲームエンド","EXT","6.9"],
["最強ゲームエンド","MAS","8.05"],
["失恋かぞえうた","BSC","3.0"],
["失恋かぞえうた","ADV","5.05"],
["失恋かぞえうた","EXT","6.4"],
["失恋かぞえうた","MAS","8.1"],
["紫電一閃","BSC","3.7"],
["紫電一閃","ADV","6.0"],
["紫電一閃","EXT","7.55"],
["紫電一閃","MAS","8.9"],
["シノビシノノメ","BSC","1.7"],
["シノビシノノメ","ADV","3.2"],
["シノビシノノメ","EXT","6.1"],
["シノビシノノメ","MAS","7.95"],
["シャルル","BSC","1.55"],
["シャルル","ADV","4.25"],
["シャルル","EXT","5.45"],
["シャルル","MAS","7.35"],
["銃弾は解を撃ち抜いて","BSC","1.8"],
["銃弾は解を撃ち抜いて","ADV","4.55"],
["銃弾は解を撃ち抜いて","EXT","6.7"],
["銃弾は解を撃ち抜いて","MAS","7.6"],
["春雷","BSC","1.0"],
["春雷","ADV","2.5"],
["春雷","EXT","3.8"],
["春雷","MAS","5.45"],
["星座が恋した瞬間を。","BSC","4.2"],
["星座が恋した瞬間を。","ADV","6.05"],
["星座が恋した瞬間を。","EXT","7.35"],
["星座が恋した瞬間を。","MAS","8.35"],
["想像だけで素晴らしいんだ","BSC","1.9"],
["想像だけで素晴らしいんだ","ADV","4.4"],
["想像だけで素晴らしいんだ","EXT","6.4"],
["想像だけで素晴らしいんだ","MAS","7.6"],
["大好きなぬいぐるみ","BSC","2.35"],
["大好きなぬいぐるみ","ADV","4.55"],
["大好きなぬいぐるみ","EXT","6.15"],
["大好きなぬいぐるみ","MAS","7.55"],
["絶え果つ花の都より","BSC","1.9"],
["絶え果つ花の都より","ADV","4.45"],
["絶え果つ花の都より","EXT","6.45"],
["絶え果つ花の都より","MAS","8.0"],
["立ち入り禁止","BSC","1.95"],
["立ち入り禁止","ADV","3.85"],
["立ち入り禁止","EXT","6.55"],
["立ち入り禁止","MAS","8.4"],
["チョコレートスマイル","BSC","2.15"],
["チョコレートスマイル","ADV","4.85"],
["チョコレートスマイル","EXT","6.5"],
["チョコレートスマイル","MAS","7.65"],
["出口入口","BSC","3.05"],
["出口入口","ADV","5.3"],
["出口入口","EXT","7.25"],
["出口入口","MAS","8.5"],
["とびきりシュガータイム","BSC","3.75"],
["とびきりシュガータイム","ADV","5.5"],
["とびきりシュガータイム","EXT","7.3"],
["とびきりシュガータイム","MAS","9.1"],
["ナイト・オブ・ロンド","BSC","1.65"],
["ナイト・オブ・ロンド","ADV","4.5"],
["ナイト・オブ・ロンド","EXT","6.05"],
["ナイト・オブ・ロンド","MAS","7.1"],
["ノルエピネフリン","BSC","3.25"],
["ノルエピネフリン","ADV","5.25"],
["ノルエピネフリン","EXT","7.75"],
["ノルエピネフリン","MAS","9.1"],
["ピースサイン","BSC","1.6"],
["ピースサイン","ADV","3.4"],
["ピースサイン","EXT","5.65"],
["ピースサイン","MAS","7.05"],
["ビター・エスケープ","BSC","2.25"],
["ビター・エスケープ","ADV","4.9"],
["ビター・エスケープ","EXT","6.35"],
["ビター・エスケープ","MAS","7.9"],
["一夜のキセキ","BSC","2.15"],
["一夜のキセキ","ADV","4.1"],
["一夜のキセキ","EXT","5.9"],
["一夜のキセキ","MAS","7.45"],
["風鈴花火","BSC","2.15"],
["風鈴花火","ADV","4.5"],
["風鈴花火","EXT","5.95"],
["風鈴花火","MAS","7.65"],
["フリップブック*ストーリー","BSC","2.35"],
["フリップブック*ストーリー","ADV","4.75"],
["フリップブック*ストーリー","EXT","6.7"],
["フリップブック*ストーリー","MAS","8.55"],
["摩天楼ノ特異点～Anti;HERO","BSC","3.45"],
["摩天楼ノ特異点～Anti;HERO","ADV","4.8"],
["摩天楼ノ特異点～Anti;HERO","EXT","6.8"],
["摩天楼ノ特異点～Anti;HERO","MAS","8.25"],
["真夏のMotion☆","BSC","2.95"],
["真夏のMotion☆","ADV","4.9"],
["真夏のMotion☆","EXT","6.3"],
["真夏のMotion☆","MAS","8.1"],
["まぼろしウインク","BSC","1.3"],
["まぼろしウインク","ADV","3.8"],
["まぼろしウインク","EXT","6.0"],
["まぼろしウインク","MAS","7.6"],
["ミカヅキ:コネクト","BSC","3.75"],
["ミカヅキ:コネクト","ADV","6.35"],
["ミカヅキ:コネクト","EXT","7.25"],
["ミカヅキ:コネクト","MAS","9.52"],
["ミラクル・スイート・スイーツ・マジック！！","BSC","2.4"],
["ミラクル・スイート・スイーツ・マジック！！","ADV","5.15"],
["ミラクル・スイート・スイーツ・マジック！！","EXT","6.6"],
["ミラクル・スイート・スイーツ・マジック！！","MAS","8.55"],
["無垢","BSC","2.7"],
["無垢","ADV","4.9"],
["無垢","EXT","7.4"],
["無垢","MAS","8.8"],
["ヤオヨロズランズ","BSC","4.7"],
["ヤオヨロズランズ","ADV","6.6"],
["ヤオヨロズランズ","EXT","8.2"],
["ヤオヨロズランズ","MAS","9.35"],
["夢色☆スパイラル!!!!!","BSC","3.45"],
["夢色☆スパイラル!!!!!","ADV","5.9"],
["夢色☆スパイラル!!!!!","EXT","7.9"],
["夢色☆スパイラル!!!!!","MAS","9.3"],
["ようこそジャパリパークへ","BSC","1.75"],
["ようこそジャパリパークへ","ADV","3.8"],
["ようこそジャパリパークへ","EXT","6.1"],
["ようこそジャパリパークへ","MAS","7.15"],
["レゾンデートル、前線より","BSC","2.0"],
["レゾンデートル、前線より","ADV","4.6"],
["レゾンデートル、前線より","EXT","6.35"],
["レゾンデートル、前線より","MAS","7.85"],
["煉獄事変","BSC","4.55"],
["煉獄事変","ADV","6.1"],
["煉獄事変","EXT","7.6"],
["煉獄事変","MAS","9.6"],
["A SHOOTING STAR","BSC","3.35"],
["A SHOOTING STAR","ADV","5.05"],
["A SHOOTING STAR","EXT","7.75"],
["Aithon","BSC","4.5"],
["Aithon","ADV","5.4"],
["Aithon","EXT","6.45"],
["Dance the Night Away","BSC","1.25"],
["Dance the Night Away","ADV","3.6"],
["Dance the Night Away","EXT","5.35"],
["Dance the Night Away","MAS","6.55"],
["Marigold","BSC","1.6"],
["Marigold","ADV","4.3"],
["Marigold","EXT","5.85"],
["Wall Street down-sizer","BSC","3.2"],
["Wall Street down-sizer","ADV","5.8"],
["Wall Street down-sizer","EXT","7.1"],
["螺子之人","BSC","3.8"],
["螺子之人","ADV","6.9"],
["螺子之人","EXT","8.4"],
["バリバリブギ ～涙のフルーツポンチ～","BSC","2.3"],
["バリバリブギ ～涙のフルーツポンチ～","ADV","4.2"],
["バリバリブギ ～涙のフルーツポンチ～","EXT","6.1"],
["バリバリブギ ～涙のフルーツポンチ～","MAS","7.05"],
["ペパーミントは私の敵","BSC","3.55"],
["ペパーミントは私の敵","ADV","5.55"],
["ペパーミントは私の敵","EXT","6.85"],
["空言の海","BSC","3.4"],
["空言の海","ADV","5.2"],
["空言の海","EXT","6.3"]]
console.log("last update 20181010")
